"""T2 - texpass_iter's selftest: exit 0, styled texels byte-identical
(max delta 0.000000), the write-head lossless.

Source: the tool's own selftest; E16-4's anchor table measured it on the
sword's anchor state (PASS, write-head lossless, 377 texels committed).

TIER CORRECTION, a finding against the dispatch: the kickoff lists this test
as hermetic and the tests-required law commit calls the selftest "re-runnable
from a fresh clone". It is not: --state, --prep and (via emit's unconditional
load_scene) --glb are required, and the repo tracks no fixture state - the
smallest real inputs are the recorded trees. Ported at the artifacts tier;
whether a tiny in-repo fixture state should exist is the advisor's call, not
a fixture this session invents.

  -> RULED (E17 Ruling 3d): the fixture was COMMISSIONED to the index-MCP build
     session, which built it at tests/fixtures/selftest_min (40 KB, one flat
     quad, generated by tests/fixtures/make_selftest_fixture.py). T2b below is
     that hermetic twin. The ruling is explicit that it ADDS: the artifacts
     tier keeps anchoring the REAL recorded state, and T2 is unchanged.

The selftest COMMITS into --state, so the state is copied to scratch and the
recorded tree is read-only (Ruling 33's ledger).
"""
import hashlib
import os
import re
import shutil

import numpy as np
import pytest

from conftest import REPO, copy_state, need, run_py, last_nonempty


@pytest.mark.artifacts
def test_t02_selftest_write_head_lossless(assets, tmp_path):
    prep = need(assets, "facet_next/E14_prep")
    glb = need(assets, "facet_next/E14_prep/prep_uv.glb")
    state_src = need(assets, "facet_next/E14_strokes/run/final/rstate_s8anchor")
    state = copy_state(state_src, tmp_path / "state")

    rc, out, err = run_py(
        "texpass_iter.py",
        ["selftest", "--state", state, "--prep", prep, "--glb", glb])
    assert rc == 0, "selftest exited %d\n%s\n%s" % (rc, out, err)

    delta_lines = [ln for ln in out.splitlines()
                   if ln.startswith("[selftest] styled-texel max delta")]
    assert len(delta_lines) == 1, "delta line not found:\n%s" % out
    assert "max delta 0.000000" in delta_lines[0], (
        "styled texels moved: %s" % delta_lines[0])

    assert last_nonempty(out).startswith("[selftest] PASS"), (
        "last line is not the selftest PASS:\n%s" % out)

    # reported, not asserted: the committed count (E16-4 measured 377 on this
    # state; the dispatch anchors exit code and delta, and the count depends
    # on the fake-inpaint blur, i.e. on scipy - a version drift there would
    # move the count without touching the write-head property under test)
    m = re.search(r"committed ([\d,]+)", delta_lines[0])
    print("T2 committed texels: %s (E16-4 recorded 377)" % (m.group(1) if m else "?"))


# ---------------------------------------------------------------------------
# T2b - the hermetic twin (E17 Ruling 3d, built E18 D2)
# ---------------------------------------------------------------------------

FIXTURE = REPO / "tests" / "fixtures" / "selftest_min"


def _tree_hashes(root):
    out = {}
    for base, dirs, names in os.walk(str(root)):
        dirs.sort()
        for n in sorted(names):
            p = os.path.join(base, n)
            with open(p, "rb") as fh:
                out[os.path.relpath(p, str(root)).replace("\\", "/")] = \
                    hashlib.sha256(fh.read()).hexdigest()
    return out


def test_t02b_selftest_hermetic_twin(tmp_path):
    """The same property as T2, on a synthetic in-repo state, in CI.

    NON-VACUOUS BY ASSERTION, not by hope. `max delta 0.000000` over an EMPTY
    styled set is 0 for free, and `holes did not shrink` passes when nothing
    was committed - so this pins both populations: the fixture carries styled
    texels before the run, and the run writes texels. That pairing is what the
    kickoff meant by a fixture rather than a file that loads.
    """
    assert FIXTURE.is_dir(), (
        "the hermetic fixture is missing at %s - regenerate it with "
        "tests/fixtures/make_selftest_fixture.py" % FIXTURE)
    before = _tree_hashes(FIXTURE)

    styled_pre = np.load(str(FIXTURE / "state" / "styled_mask.npy"))
    assert styled_pre.any(), (
        "the fixture carries no styled texels, so the selftest's own assertion "
        "would pass over an empty set - a check that cannot fail")

    state = tmp_path / "state"
    shutil.copytree(str(FIXTURE / "state"), str(state))
    rc, out, err = run_py(
        "texpass_iter.py",
        ["selftest", "--state", state,
         "--prep", FIXTURE / "prep", "--glb", FIXTURE / "mesh_uv.glb"])
    assert rc == 0, "hermetic selftest exited %d\n%s\n%s" % (rc, out, err)

    delta_lines = [ln for ln in out.splitlines()
                   if ln.startswith("[selftest] styled-texel max delta")]
    assert len(delta_lines) == 1, "delta line not found:\n%s" % out
    assert "max delta 0.000000" in delta_lines[0], (
        "styled texels moved: %s" % delta_lines[0])
    assert last_nonempty(out).startswith("[selftest] PASS"), out

    m = re.search(r"committed ([\d,]+)", delta_lines[0])
    assert m, "no committed count in:\n%s" % delta_lines[0]
    committed = int(m.group(1).replace(",", ""))
    # 512 is the WHOLE hole half of a 32x32 atlas. It is a structural number,
    # not a tuned one: every hole texel on this quad is visible, faces the
    # camera at 1.0 and projects far more than --edge-dist from the rendered
    # figure edge, so a partial count is a real change in the write head's
    # acceptance rather than a tolerance to widen.
    assert committed == 512, (
        "hermetic selftest committed %d texels, expected the full hole half "
        "(512). A partial commit is a finding, not a tolerance." % committed)
    assert "holes 512 -> 0" in out, out

    # the committed fixture is an INPUT and must come back untouched: the tool
    # writes into --state, which is why --state is the copy
    assert _tree_hashes(FIXTURE) == before, (
        "the run modified the committed fixture tree")
