#!/usr/bin/env python
"""Render the canonical handbook into the Starlight site.

`docs/handbook/*.md` is the ONE copy of the handbook. This script renders it into
`site/src/content/docs/handbook/` for the published site; it never edits the source
and the site copy is never hand-edited.

**Why generated rather than duplicated.** Two hand-maintained copies of the same
prose drift, and this repo has paid for drift repeatedly. There is a sharper reason
here: `docs/handbook/` is inside the claims sweep's file set (`facet_index.py claims`
treats it as current-state and gates on it), and everything under `site/` is
**outside** that set. If the handbook were authored in `site/`, the repo's own
staleness gate could not see its own handbook. Keeping the source under `docs/` keeps
it gated; rendering into `site/` keeps it published.

Site-only pages — `getting-started.md`, `reference.md`, `reading-the-record.md` —
are authored directly in `site/` and are left alone. Only the three files in
SYNCED below are overwritten.

    python docs/handbook/sync_to_site.py          # write
    python docs/handbook/sync_to_site.py --check  # exit 1 if the site copy is stale

`--check` is the drift gate. Run it before any commit that touches the handbook.
"""

import argparse
import io
import os
import re
import sys

REPO_BLOB = "https://github.com/mcp-tool-shop-org/facet/blob/main"
REPO_TREE = "https://github.com/mcp-tool-shop-org/facet/tree/main"

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
SRC = os.path.join(REPO, "docs", "handbook")
DST = os.path.join(REPO, "site", "src", "content", "docs", "handbook")

# name -> (title, description, sidebar order)
SYNCED = {
    "index": (
        "The facet handbook",
        "A styled 2D concept goes in; a textured 3D asset comes out. The route, stage by stage, with every claim traced to a numbered experiment.",
        0,
    ),
    "subjects": (
        "The subjects",
        "Four subject classes through the route — character, galleon, dragon, longsword — with their numbers and, crucially, their denominators.",
        2,
    ),
    "profiles": (
        "Subject profiles",
        "The profile loader, the decision forms a subject must answer, and the registry sweep that gates them.",
        3,
    ),
}

# Link rewrites, applied in order. Repo-relative markdown links become GitHub URLs;
# sibling handbook links become site routes.
REWRITES = [
    (re.compile(r"\]\(\.\./\.\./README\.md\)"), "](%s/README.md)" % REPO_BLOB),
    (re.compile(r"\]\(\.\./\.\./canon/([^)]+)\)"), r"](%s/canon/\1)" % REPO_BLOB),
    (re.compile(r"\]\(\.\./experiments/\)"), "](%s/docs/experiments)" % REPO_TREE),
    (re.compile(r"\]\(\.\./experiments/([^)]+)\)"), r"](%s/docs/experiments/\1)" % REPO_BLOB),
    (re.compile(r"\]\(\.\./([A-Za-z0-9_-]+\.md)\)"), r"](%s/docs/\1)" % REPO_BLOB),
    (re.compile(r"\]\(profiles\.md\)"), "](../profiles/)"),
    (re.compile(r"\]\(subjects\.md\)"), "](../subjects/)"),
    (re.compile(r"\]\(index\.md\)"), "](../)"),
]

BANNER = (
    "<!-- GENERATED by docs/handbook/sync_to_site.py from docs/handbook/%s.md.\n"
    "     Do not edit this file. Edit the source and re-run the script — the source\n"
    "     is inside the claims sweep's file set and this copy is not. -->\n"
)


def esc(s):
    """Quote a YAML scalar safely without pulling in a YAML dependency."""
    return '"%s"' % s.replace("\\", "\\\\").replace('"', '\\"')


def render(name):
    title, desc, order = SYNCED[name]
    with io.open(os.path.join(SRC, name + ".md"), encoding="utf-8") as fh:
        body = fh.read().replace("\r\n", "\n")

    # Starlight renders the frontmatter title as the page h1, so drop the source's
    # own leading h1 rather than shipping two.
    body = re.sub(r"\A#\s+[^\n]*\n+", "", body)

    # Scan the SOURCE for repo-relative links no rule handles, before rewriting —
    # scanning afterwards would flag the rules' own output (`../profiles/`), which is
    # the "guard that fires on a correct input" this repo has already paid for once.
    stray = [
        m.group(0)
        for m in re.finditer(r"\]\([^)#][^)]*\)", body)
        if not m.group(0).startswith("](http")
        and not any(pat.match(m.group(0)) for pat, _ in REWRITES)
    ]
    if stray:
        raise SystemExit(
            "ANDON: %s.md carries %d link(s) with no rewrite rule — the site copy "
            "would ship dead links. First three: %s"
            % (name, len(stray), stray[:3])
        )

    for pat, rep in REWRITES:
        body = pat.sub(rep, body)

    front = "---\ntitle: %s\ndescription: %s\nsidebar:\n  order: %d\n---\n\n" % (
        esc(title),
        esc(desc),
        order,
    )
    return front + (BANNER % name) + "\n" + body


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if any site copy differs from what would be written",
    )
    args = ap.parse_args()

    os.makedirs(DST, exist_ok=True)
    stale = []
    for name in sorted(SYNCED):
        want = render(name)
        out = os.path.join(DST, name + ".md")
        have = None
        if os.path.exists(out):
            with io.open(out, encoding="utf-8") as fh:
                have = fh.read().replace("\r\n", "\n")
        if have == want:
            print("  ok     %s.md" % name)
            continue
        stale.append(name)
        if args.check:
            print("  STALE  %s.md" % name)
        else:
            with io.open(out, "w", encoding="utf-8", newline="\n") as fh:
                fh.write(want)
            print("  wrote  %s.md  (%d bytes)" % (name, len(want)))

    if args.check and stale:
        print(
            "\nANDON: %d site handbook page(s) differ from docs/handbook/. "
            "Run `python docs/handbook/sync_to_site.py` and commit the result."
            % len(stale)
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
