#!/usr/bin/env python
"""Generate the hermetic selftest fixture (E17 Ruling 3d's commission, E18 D2).

WHY THIS EXISTS. T2 replays `texpass_iter selftest` - the write head's
losslessness on styled texels - and the E17 session found it is NOT hermetic:
`--state`, `--prep` and `--glb` are required recorded inputs, so the test could
only run against the trees under E:\\AI\\training, which are not in git and not
in CI. The ruling commissioned "a synthetic minimal in-repo state (tiny mesh,
tiny atlas, tiny prep) so the write-head's losslessness runs hermetic in CI",
and was explicit that the artifacts-tier T2 keeps anchoring the REAL recorded
state: THE FIXTURE ADDS A TWIN, IT REPLACES NOTHING.

WHAT IT BUILDS, and why each number is what it is. The subject is one flat quad
facing the camera at yaw 90 - the simplest geometry that exercises every gate
the write head runs, rather than the smallest file that loads:

  glb        4 verts / 2 tris in the plane x = 1, y in [-1, 1], z in [-0.6, 0.6].
             load_scene swizzles [x, -z, y] and divides by max|component|, so
             this lands as X = 0.5 (facing the camera at yaw 90), Y in
             [-0.3, 0.3] and Z in [-0.5, 0.5]. The Y half-extent is 0.3 rather
             than 0.5 ON PURPOSE: emit fits the frame to the Z extent
             (v_ext = 1.204, h_ext = v_ext * 752/1024 = 0.884), so a quad half a
             unit wide would project past the frame edge and the edge-distance
             guard would be measured against the CROP rather than against the
             figure.
  atlas      RES x RES, two halves in u: the styled half and the hole half, both
             far from the 0.42 background in max-channel distance. That
             distance is load-bearing - commit keys its trust mask with
             |edited - bg| > 0.06, and an unpainted hole rendering AT the
             background value is indistinguishable from background by colour
             (the hazard texpass_iter's own comments name). A fixture painted
             hole-grey would silently commit nothing.
  holes      the u >= 0.5 half. Disjoint from styled, which is the invariant the
             real state carries: commit sets styled and clears holes for exactly
             what it wrote.
  styled     the u < 0.5 half - NON-EMPTY on purpose. The selftest's assertion
             is `max delta over pre_styled`, and over an empty set that is 0 for
             free: a check that cannot fail.
  prep       meta.json (lo/hi/maxabs of the swizzled bbox, which is what commit
             decodes pos against), mask.npy (all figure - the quad's UV covers
             the atlas), pos.npy and nor.npy - both derived ANALYTICALLY from
             the same quad, not baked, so the fixture has no dependence on a
             baking tool.

Run:  python tests/fixtures/make_selftest_fixture.py
The generated bytes are committed. This script documents and reproduces them;
byte-equality across numpy/pillow/trimesh versions is NOT claimed, and the
committed files are the fixture.
"""
import json
import os

import numpy as np
import trimesh
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "selftest_min")

RES = 32                      # tiny on purpose; the commission's own word
BG = 0.42                     # emit's non-hit fill, and project_twins' hole grey
STYLED_RGB = (0.16, 0.55, 0.82)
HOLE_RGB = (0.78, 0.36, 0.18)

# the quad, in RAW glTF coordinates. load_scene does v = [x, -z, y] / vmax * 0.5
Y_HALF = 0.6                  # -> scene Y half-extent 0.3
Z_HALF = 1.0                  # -> scene Z half-extent 0.5


def quad():
    """(vertices, faces, uv). u runs with scene +Y (right), v with scene +Z (up)."""
    verts = np.array([
        [1.0, -Z_HALF,  Y_HALF],      # u0 v0
        [1.0, -Z_HALF, -Y_HALF],      # u1 v0
        [1.0,  Z_HALF, -Y_HALF],      # u1 v1
        [1.0,  Z_HALF,  Y_HALF],      # u0 v1
    ], dtype=np.float64)
    faces = np.array([[0, 1, 2], [0, 2, 3]], dtype=np.int64)
    uv = np.array([[0.0, 0.0], [1.0, 0.0], [1.0, 1.0], [0.0, 1.0]],
                  dtype=np.float64)
    return verts, faces, uv


def swizzle(v):
    return np.stack([v[:, 0], -v[:, 2], v[:, 1]], axis=1)


def main():
    os.makedirs(os.path.join(OUT, "state"), exist_ok=True)
    os.makedirs(os.path.join(OUT, "prep"), exist_ok=True)

    verts, faces, uv = quad()
    mesh = trimesh.Trimesh(vertices=verts, faces=faces, process=False)
    mesh.visual = trimesh.visual.TextureVisuals(uv=uv)
    with open(os.path.join(OUT, "mesh_uv.glb"), "wb") as fh:
        fh.write(trimesh.exchange.gltf.export_glb(
            trimesh.Scene(mesh), include_normals=True))

    # ---- the swizzled bbox, which is what meta.json describes ---------------
    s = swizzle(verts)
    vmax = float(np.abs(verts).max())
    lo, hi = s.min(axis=0), s.max(axis=0)
    # newline="\n" is load-bearing, not tidiness: .gitattributes pins this repo
    # to LF on both sides and T6 tests that no tracked text file carries CRLF.
    # The first run of this generator wrote meta.json through the platform
    # default and git said so on the very next `add`.
    with open(os.path.join(OUT, "prep", "meta.json"), "w",
              encoding="ascii", newline="\n") as fh:
        json.dump({"res": RES, "lo": lo.tolist(), "hi": hi.tolist(),
                   "maxabs": vmax,
                   "_note": "synthetic hermetic fixture (E18 D2); one flat quad"},
                  fh, indent=1, sort_keys=True)
        fh.write("\n")

    # ---- texel grids --------------------------------------------------------
    # emit samples the atlas at ax = u*RES - 0.5, ay = (1-v)*RES - 0.5, so texel
    # (row, col) is u = (col+0.5)/RES, v = 1 - (row+0.5)/RES. pos/nor must use
    # the same convention or the fixture would test a shifted mapping.
    col = (np.arange(RES) + 0.5) / RES
    row = 1.0 - (np.arange(RES) + 0.5) / RES
    u = np.broadcast_to(col[None, :], (RES, RES))
    v = np.broadcast_to(row[:, None], (RES, RES))

    # scene-space point of the quad at (u, v), then back to the swizzled raw
    # frame commit decodes into: P_scene = S / vmax * 0.5
    sx = np.full((RES, RES), 1.0)                    # swizzled X, constant
    sy = -Y_HALF + 2.0 * Y_HALF * u                  # swizzled Y
    sz = -Z_HALF + 2.0 * Z_HALF * v                  # swizzled Z
    S = np.stack([sx, sy, sz], axis=-1)
    span = np.where((hi - lo) == 0, 1.0, hi - lo)    # X has zero extent
    pos = ((S - lo) / span).astype(np.float32)
    np.save(os.path.join(OUT, "prep", "pos.npy"), pos)

    nor = np.zeros((RES, RES, 3), dtype=np.float32)
    nor[..., 0] = 1.0                                # +X, encoded (n+1)/2
    nor[..., 1] = 0.5
    nor[..., 2] = 0.5
    np.save(os.path.join(OUT, "prep", "nor.npy"), nor)

    mask = np.ones((RES, RES, 3), dtype=np.float32)  # the UV covers the atlas
    np.save(os.path.join(OUT, "prep", "mask.npy"), mask)

    # ---- the state ----------------------------------------------------------
    hole = u >= 0.5
    atlas = np.empty((RES, RES, 3), dtype=np.float32)
    atlas[~hole] = STYLED_RGB
    atlas[hole] = HOLE_RGB
    Image.fromarray((atlas * 255).round().astype(np.uint8)).save(
        os.path.join(OUT, "state", "atlas.png"))
    Image.fromarray((hole * 255).astype(np.uint8)).save(
        os.path.join(OUT, "state", "holes.png"))
    np.save(os.path.join(OUT, "state", "styled_mask.npy"), ~hole)

    total = 0
    for base, _, names in os.walk(OUT):
        for n in names:
            total += os.path.getsize(os.path.join(base, n))
    print("fixture written to %s" % OUT)
    print("  res %d, styled texels %d, hole texels %d"
          % (RES, int((~hole).sum()), int(hole.sum())))
    print("  total %d bytes" % total)


if __name__ == "__main__":
    main()
