#!/usr/bin/env python
"""Generate the hermetic measurement fixtures (E27, the measurement MCP arc).

WHY THIS EXISTS. The measurement server (tools/measure_mcp.py) wraps instruments
whose recorded subjects live under E:\\AI\\training - trees that are not in git
and not in CI. E18 D2's selftest_min proved the pattern: a synthetic minimal
in-repo subject lets the wrapped path run hermetic in CI, and THE FIXTURE ADDS
A TWIN, IT REPLACES NOTHING - the artifacts tier keeps anchoring recorded
states. This generator builds measure_min/, the measurement server's twin.

WHAT IT BUILDS, and why each piece is what it is:

  meshes/     six tiny GLBs for mesh_stats (and for the shell-census
              cross-check the E27 predictions file commits to):
    cube.glb        a closed box, BUILT FACE-SPLIT the way a real export
                    arrives: 24 explicit vertices, each face its own island,
                    because trimesh's own box exports with its 8 shared
                    vertices intact and demonstrates nothing (measured - the
                    first cut of this generator did exactly that and
                    components_unwelded read 1). Welded: 1 component, 8
                    verts, watertight. Unwelded: SIX vertex-islands - the
                    weld law made visible on the simplest possible subject.
    pinch.glb       two boxes sharing exactly ONE corner vertex. The subject the
                    two shell definitions disagree about by construction:
                    joined by a shared vertex (1) but not by any shared
                    manifold edge (2).
    twoshell.glb    two disjoint boxes: 2 under both definitions.
    nonmanifold.glb a box with a triangular fin glued onto one existing edge:
                    that edge borders three faces. mesh_stats does not measure
                    this; the topology family does, and the fixture exists so
                    the census cross-check has a non-manifold subject.
    sheet.glb       one flat open quad: boundary edges, not watertight.
    sliver.glb      a quad whose silhouette is tiny against the default face
                    rect, so mesh_stats' rect_frac_of_figure > 1 warning FIRES
                    - the fixture that proves warnings are surfaced, not
                    swallowed.
  prep/       a bake-prep for reach_ceiling and texel_provenance, the E18 D2
              quad re-derived self-contained: prep_uv.glb + meta.json (with the
              crop/crop_res keys e08_ceiling reads) + mask/pos/nor.npy, all
              ANALYTIC - no baking tool in the loop. The quad faces canonical
              +X, so a yaw-90 camera sees every texel at facing 1.0 and a
              yaw-0/180 camera sees it edge-on at facing 0.0: the reach ladder
              N2 (yaws 0,180) -> 0 texels, N4 (adds 90,270) -> ALL texels, and
              both numbers are exact by construction, not tuned.
  state/      a one-stroke brush state for texel_provenance: stage-1 styled the
              u < 0.5 half of the atlas, the u >= 0.5 half is holes, and one
              job (yaw 90) claims the holes its edge-distance guard admits.
              TWINS therefore counts exactly RES*RES/2 texels, and
              TWINS + BRUSH + DILATION = RES*RES, whatever the brush claims.
  report/     one view for gate1_sheet: UNIFORM-colour twin and asset panels
              under a centered square mask. Uniform operands make the dE
              statistics degenerate on purpose - median == mean == p90, and
              every pixel is under the over-10 threshold - so the wrap test
              asserts identities the sheet math cannot fake, plus figure_px
              exactly equal to the mask's own area.

Run:  python tests/fixtures/make_measure_fixture.py
The generated bytes are committed. This script documents and reproduces them;
byte-equality across numpy/pillow/trimesh versions is NOT claimed, and the
committed files are the fixture (the selftest_min rule).
"""
import json
import os

import numpy as np
import trimesh
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "measure_min")

RES = 32                  # atlas resolution; tiny on purpose
JOB_W = JOB_H = 64        # the brush job frame
BG = 0.42                 # the route's non-hit grey
REPORT_RES = 32
MASK_HALF = 12            # report mask: 24x24 centered square -> 576 px exactly


def save_glb(mesh_or_scene, path):
    scene = (mesh_or_scene if isinstance(mesh_or_scene, trimesh.Scene)
             else trimesh.Scene(mesh_or_scene))
    with open(path, "wb") as fh:
        fh.write(trimesh.exchange.gltf.export_glb(scene, include_normals=True))


def box_at(origin, size=1.0):
    b = trimesh.creation.box(extents=[size, size, size])
    b.apply_translation(np.asarray(origin, dtype=np.float64)
                        + size / 2.0)
    return b


def box_facesplit(origin, size=1.0):
    """A box with every face its own vertex island - the shape a textured
    GLB export actually has after per-seam splitting."""
    b = box_at(origin, size)
    f = np.asarray(b.faces)
    v = np.asarray(b.vertices)
    # adjacent face pairs share a quad: keep quads together, split the six
    # quads apart. Faces come as 12 triangles, two per axis-aligned quad,
    # grouped by their normal direction.
    n = np.asarray(b.face_normals).round(6)
    groups = {}
    for i, nv in enumerate(map(tuple, n)):
        groups.setdefault(nv, []).append(i)
    if len(groups) != 6:
        raise AssertionError("ANDON: a box has six face normals, found %d"
                             % len(groups))
    new_v, new_f = [], []
    for idx in groups.values():
        tri = f[idx]
        used = np.unique(tri)
        remap = {int(o): len(new_v) + j for j, o in enumerate(used)}
        new_v.extend(v[used])
        new_f.extend([[remap[int(a)], remap[int(b_)], remap[int(c)]]
                      for a, b_, c in tri])
    return trimesh.Trimesh(vertices=np.asarray(new_v),
                           faces=np.asarray(new_f, dtype=np.int64),
                           process=False)


def concat(meshes):
    m = trimesh.util.concatenate(meshes)
    return trimesh.Trimesh(vertices=np.asarray(m.vertices),
                           faces=np.asarray(m.faces), process=False)


def meshes():
    d = os.path.join(OUT, "meshes")
    os.makedirs(d, exist_ok=True)

    save_glb(box_facesplit([0, 0, 0]), os.path.join(d, "cube.glb"))

    # pinch: box B's min corner IS box A's max corner (1,1,1). After a
    # position-weld the two copies of that corner merge into one vertex, and no
    # edge is shared: vertex-census 1, manifold-edge census 2.
    save_glb(concat([box_at([0, 0, 0]), box_at([1, 1, 1])]),
             os.path.join(d, "pinch.glb"))

    # two shells: strictly disjoint, a half-unit gap
    save_glb(concat([box_at([0, 0, 0]), box_at([1.5, 0, 0])]),
             os.path.join(d, "twoshell.glb"))

    # non-manifold: a fin glued onto the top-front edge of the cube. The edge
    # (1,0,1)-(0,0,1)... use exact box vertices: find the two verts of one top
    # edge and add an apex above the cube.
    cube = box_at([0, 0, 0])
    v = np.asarray(cube.vertices)
    f = np.asarray(cube.faces)
    top = np.where(np.isclose(v[:, 2], 1.0) & np.isclose(v[:, 1], 0.0))[0]
    if len(top) != 2:
        raise AssertionError("ANDON: expected exactly 2 verts on the chosen "
                             "edge, found %d" % len(top))
    apex = np.array([[0.5, -0.5, 1.5]])
    v2 = np.vstack([v, apex])
    fin = np.array([[top[0], top[1], len(v)]], dtype=np.int64)
    save_glb(trimesh.Trimesh(vertices=v2, faces=np.vstack([f, fin]),
                             process=False),
             os.path.join(d, "nonmanifold.glb"))

    # sheet: one open quad in the x=1 plane (the D2 quad, no UV needed here)
    quad_v = np.array([[1.0, -1.0, 0.6], [1.0, -1.0, -0.6],
                       [1.0, 1.0, -0.6], [1.0, 1.0, 0.6]])
    quad_f = np.array([[0, 1, 2], [0, 2, 3]], dtype=np.int64)
    save_glb(trimesh.Trimesh(vertices=quad_v, faces=quad_f, process=False),
             os.path.join(d, "sheet.glb"))

    # sliver: silhouette area far below the default face rect's area, so the
    # rect_frac_of_figure > 1 warning fires. Extents 0.02 against maxabs 1.
    sl_v = np.array([[1.0, -0.02, 0.02], [1.0, -0.02, -0.02],
                     [1.0, 0.02, -0.02], [1.0, 0.02, 0.02]])
    save_glb(trimesh.Trimesh(vertices=sl_v, faces=quad_f, process=False),
             os.path.join(d, "sliver.glb"))


# ---- the quad prep (E18 D2's construction, self-contained) -----------------
Y_HALF = 0.6      # raw glTF Y half-extent -> scene Y half 0.3
Z_HALF = 1.0      # raw glTF Z half-extent -> scene Z half 0.5


def quad_uv():
    verts = np.array([
        [1.0, -Z_HALF,  Y_HALF],
        [1.0, -Z_HALF, -Y_HALF],
        [1.0,  Z_HALF, -Y_HALF],
        [1.0,  Z_HALF,  Y_HALF],
    ], dtype=np.float64)
    faces = np.array([[0, 1, 2], [0, 2, 3]], dtype=np.int64)
    uv = np.array([[0.0, 0.0], [1.0, 0.0], [1.0, 1.0], [0.0, 1.0]],
                  dtype=np.float64)
    return verts, faces, uv


def swizzle(v):
    return np.stack([v[:, 0], -v[:, 2], v[:, 1]], axis=1)


def prep():
    d = os.path.join(OUT, "prep")
    os.makedirs(d, exist_ok=True)
    verts, faces, uv = quad_uv()
    mesh = trimesh.Trimesh(vertices=verts, faces=faces, process=False)
    mesh.visual = trimesh.visual.TextureVisuals(uv=uv)
    save_glb(mesh, os.path.join(d, "prep_uv.glb"))

    s = swizzle(verts)
    vmax = float(np.abs(verts).max())
    lo, hi = s.min(axis=0), s.max(axis=0)
    # crop selects NO texels on purpose: the quad sits at canonical X 0.5, which
    # projects to px ~977 in the 1024 frame, far outside [0, 64) - so the head
    # band is empty and the body floor governs every texel.
    with open(os.path.join(d, "meta.json"), "w", encoding="ascii",
              newline="\n") as fh:
        json.dump({"res": RES, "lo": lo.tolist(), "hi": hi.tolist(),
                   "maxabs": vmax, "crop": [0, 0, 64, 64], "crop_res": 1024,
                   "_note": "synthetic hermetic fixture (E27); one flat quad"},
                  fh, indent=1, sort_keys=True)
        fh.write("\n")

    col = (np.arange(RES) + 0.5) / RES
    row = 1.0 - (np.arange(RES) + 0.5) / RES
    u = np.broadcast_to(col[None, :], (RES, RES))
    v = np.broadcast_to(row[:, None], (RES, RES))

    sx = np.full((RES, RES), 1.0)
    sy = -Y_HALF + 2.0 * Y_HALF * u
    sz = -Z_HALF + 2.0 * Z_HALF * v
    S = np.stack([sx, sy, sz], axis=-1)
    span = np.where((hi - lo) == 0, 1.0, hi - lo)
    np.save(os.path.join(d, "pos.npy"), ((S - lo) / span).astype(np.float32))

    nor = np.zeros((RES, RES, 3), dtype=np.float32)
    nor[..., 0] = 1.0            # +X, encoded (n+1)/2
    nor[..., 1] = 0.5
    nor[..., 2] = 0.5
    np.save(os.path.join(d, "nor.npy"), nor)
    np.save(os.path.join(d, "mask.npy"), np.ones((RES, RES, 3),
                                                 dtype=np.float32))
    return lo, hi, vmax


def basis(yaw_d, el_d):
    """texel_provenance's own camera basis, reproduced for cam.json's fields."""
    th, el = np.radians(yaw_d), np.radians(el_d)
    cd = np.array([np.sin(th) * np.cos(el), -np.cos(th) * np.cos(el),
                   np.sin(el)])
    look = -cd / np.linalg.norm(cd)
    right = np.cross(look, [0.0, 0.0, 1.0])
    right /= np.linalg.norm(right) + 1e-12
    up = np.cross(right, look)
    return look, right, up / (np.linalg.norm(up) + 1e-12)


def state():
    d = os.path.join(OUT, "state")
    j = os.path.join(d, "job_y+090_e+00")
    os.makedirs(j, exist_ok=True)

    col = (np.arange(RES) + 0.5) / RES
    u = np.broadcast_to(col[None, :], (RES, RES))
    hole = u >= 0.5
    atlas = np.empty((RES, RES, 3), dtype=np.float32)
    atlas[~hole] = (0.16, 0.55, 0.82)
    atlas[hole] = BG
    Image.fromarray((atlas * 255).round().astype(np.uint8)).save(
        os.path.join(d, "stage1.png"))
    Image.fromarray((hole * 255).astype(np.uint8)).save(
        os.path.join(d, "stage1_holes.png"))
    np.save(os.path.join(d, "stage1_styled_mask.npy"), ~hole)

    # the job camera: yaw 90 looks straight at the quad's +X face. bmid is the
    # quad's canonical centre; the extents frame the whole quad with margin.
    cam = {"yaw": 90.0, "el": 0.0, "bmid": [0.5, 0.0, 0.0],
           "h_ext": 1.2, "v_ext": 1.2, "W": JOB_W, "H": JOB_H}
    with open(os.path.join(j, "cam.json"), "w", encoding="ascii",
              newline="\n") as fh:
        json.dump(cam, fh, indent=1, sort_keys=True)
        fh.write("\n")

    # inpainted: an 8 px background border (the corner samples the tool keys
    # its background estimate from) around a solidly painted interior. The
    # minimum_filter(5) erosion plus the edge-distance floor of 4 px means only
    # holes projecting well inside the painted region are claimed.
    img = np.full((JOB_H, JOB_W, 3), BG, dtype=np.float32)
    img[8:-8, 8:-8] = (0.80, 0.30, 0.20)
    Image.fromarray((img * 255).round().astype(np.uint8)).save(
        os.path.join(j, "inpainted.png"))
    Image.fromarray(np.full((JOB_H, JOB_W), 255, dtype=np.uint8)).save(
        os.path.join(j, "mask.png"))


def report():
    for sub in ("twins", "asset", "prov", "masks"):
        os.makedirs(os.path.join(OUT, "report", sub), exist_ok=True)
    R = REPORT_RES

    def solid(rgb):
        a = np.zeros((R, R, 3), dtype=np.uint8)
        a[:] = rgb
        return Image.fromarray(a)

    # close colours on purpose: constant dE well under 10, so pct_over_10 and
    # pct_over_23 are exactly 0.0 and median == mean == p90.
    solid((60, 120, 180)).save(os.path.join(OUT, "report", "twins",
                                            "twin_0.png"))
    solid((66, 116, 174)).save(os.path.join(OUT, "report", "asset",
                                            "final_0.png"))
    solid((128, 180, 90)).save(os.path.join(OUT, "report", "prov",
                                            "prov_0.png"))
    mask = np.zeros((R, R), dtype=np.uint8)
    c0, c1 = R // 2 - MASK_HALF, R // 2 + MASK_HALF
    mask[c0:c1, c0:c1] = 255
    Image.fromarray(mask).save(os.path.join(OUT, "report", "masks",
                                            "w3clay_0.png"))


def main():
    os.makedirs(OUT, exist_ok=True)
    meshes()
    prep()
    state()
    report()
    total, count = 0, 0
    for base, _, names in os.walk(OUT):
        for n in names:
            total += os.path.getsize(os.path.join(base, n))
            count += 1
    print("fixture written to %s" % OUT)
    print("  %d files, %d bytes total" % (count, total))
    print("  mask square: %d px  (report figure_px, exact)"
          % ((2 * MASK_HALF) ** 2))
    print("  atlas: %d texels, styled %d, holes %d"
          % (RES * RES, RES * RES // 2, RES * RES // 2))


if __name__ == "__main__":
    main()
