#!/usr/bin/env python
"""facet_index — the derived index over the markdown record.

WHAT THIS IS. `docs/index/facet.db` is a SQLite+FTS5 map of this repo's record,
GENERATED by this file and never hand-edited. The markdown stays canonical:
corrections in place, prose holdings, the evidence trail. The database exists so a
session can *query* instead of reading, and then read the forty lines the query
pointed at rather than the six hundred it would have skimmed. The design ruling is
docs/context-architecture.md.

THE DAY IT IS HAND-EDITED IT IS WRONG BY DEFINITION. Every fold regenerates it;
`verify` gates the regeneration; a build that fails verify does not commit.

THIS FILE NEVER WRITES TO THE RECORD. It parses by the record's own conventions and
reports what it could not parse. A builder that "fixes" a source document while
parsing it has failed — malformed-by-convention text is a report item, never an edit.

WHAT IT PARSES, AND WHERE THE CONVENTIONS COME FROM. Nothing here was invented; each
pattern is the shape the record already uses:

  ## Ruling 25 — TITLE (2026-08-07)          numbered rulings   E04/E10/E11/E12/E10off
  **25c — TITLE.** body...                   lettered subs      E12 mostly, E04/E10off
  > ### Amendment 32 (advisor, 2026-08-04)   amendments         E08
  ## Post-ingest addenda 3 (2026-08-07, …)   addenda            E11
  ## Session handoff 15 (2026-08-07) — …     handoffs           E04/E12 kickoffs
  **A law's statement.** what it was paid…   laws               CLAUDE.md
  tools.<tool>.<key> = {value, why, from}    decisions          profiles/*.json

DETERMINISM IS A CONTRACT, NOT AN ASPIRATION. Two builds from an unchanged record
must be byte-identical. Everything that could vary is pinned: the file list is an
explicit sorted constant, every traversal is `sorted()`, every insert order is fixed,
the whole build is ONE transaction, and no timestamp or random value is ever written.
`verify` tests this rather than trusting it, with a pre-registered `.dump` fallback
if SQLite's own file header (a change counter, an implementation detail) defeats byte
equality.

ANCHORS COME IN TWO FORMS AND THAT IS DELIBERATE. `anchor` is the human label a
session reads and cites ("Ruling 25c"). `locator` is the exact string findable in the
file ("**25c —"), because GitHub mints anchors for `#`-headings only and a bold lead
is not one. The dangling-pointer gate checks `locator`; the query output prints
`anchor`.

Standards compliance
  PIN_PER_STEP        the DB is a pure function of the record at a commit; this file
                      is committed beside it; `build` takes no tuning parameters.
  ANDON_AUTHORITY     `verify` exits non-zero on any of four legs and prints the
                      failing evidence; a parse it cannot do is reported, never
                      papered over.
  NAMED_COMPENSATORS  writes exactly one path (docs/index/facet.db); undo is deleting
                      it. The record is opened read-only.
  DECOMPOSE_BY_SECRETS the parser knows conventions, the schema knows ontology, the
                      verifier knows neither's internals — it re-derives its counts
                      from the record with its own greps.
  UNCERTAINTY_GATED_HUMANS parse limitations print as findings for the advisor's eye.
  EXTERNAL_VERIFIER   the seeded question set is advisory-authored and its expected
                      answers are keyed to record anchors this file never reads as
                      input; counts are checked against independent greps.
"""
import argparse
import io
import json
import os
import re
import sqlite3
import sys
import unicodedata

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
DB_REL = "docs/index/facet.db"

# ---------------------------------------------------------------------------
# The record's own file list. Explicit and sorted rather than globbed, so the
# insert order is a property of this file rather than of a filesystem.
# ---------------------------------------------------------------------------

# arc -> ruling document carrying `## Ruling N` headers
NUMBERED_RULING_FILES = [
    ("E04", "docs/experiments/E04-ruling.md"),
    ("E10", "docs/experiments/E10-ruling.md"),
    ("E10-offsurface", "docs/experiments/E10-offsurface-ruling.md"),
    ("E11", "docs/experiments/E11-ruling.md"),
    ("E12", "docs/experiments/E12-ruling.md"),
]

# arc -> document carrying `> ### Amendment N (author, date)` headers
AMENDMENT_FILES = [
    ("E08", "docs/experiments/E08-ruling-gate0.md"),
]

# ruling-class documents that carry NO numbered rulings — topical `##` sections
# only. They enter the index as prose sections, and that asymmetry is a reported
# finding, not a defect this parser can fix.
TOPICAL_RULING_FILES = [
    ("E01", "docs/experiments/E01-ruling-gate1.md"),
    ("E02", "docs/experiments/E02-ruling-gate1.md"),
    ("E06", "docs/experiments/E06-ruling-gate1.md"),
    ("E07", "docs/experiments/E07-ruling-gate1.md"),
    ("E08", "docs/experiments/E08-director-canon-ruling.md"),
]

HANDOFF_FILES = [
    ("E04", "docs/experiments/E04-executor-kickoff.md"),
    ("E12", "docs/experiments/E12-executor-kickoff.md"),
]

LAW_FILES = ["CLAUDE.md"]

PROFILE_FILES = ["profiles/beast.json", "profiles/character.json", "profiles/ship.json"]

# prose corpora indexed for FTS with no ontology row of their own
PROSE_FILES = [
    "README.md",
    "docs/context-architecture.md",
    "docs/experiments/README.md",
    "docs/handbook/index.md",
    "docs/handbook/profiles.md",
    "docs/handbook/subjects.md",
    "docs/profiles-design.md",
    "docs/style-registers.md",
]

# every markdown file of the record, for artifact / phenomenon extraction. Built
# by a sorted walk so the traversal cannot depend on directory order.
def record_markdown():
    out = []
    for rel in ["CLAUDE.md", "README.md"]:
        out.append(rel)
    for root in ["docs"]:
        for dirpath, dirnames, filenames in os.walk(os.path.join(REPO, root)):
            dirnames.sort()
            for fn in sorted(filenames):
                if fn.endswith(".md"):
                    p = os.path.join(dirpath, fn)
                    out.append(os.path.relpath(p, REPO).replace("\\", "/"))
    return sorted(set(out))


# ---------------------------------------------------------------------------
# reading helpers
# ---------------------------------------------------------------------------

def read(rel):
    with io.open(os.path.join(REPO, rel), encoding="utf-8") as fh:
        return fh.read().replace("\r\n", "\n")


def lines_of(rel):
    return read(rel).split("\n")


DASH = "[—–-]"          # em dash, en dash, hyphen — the record uses all three
BOLD_LEAD = re.compile(r"^\*\*")


def one_line(text, limit=240):
    """Collapse to a single line. Holdings are quoted in query output."""
    t = re.sub(r"\s+", " ", text).strip()
    t = t.strip(" .")
    if len(t) > limit:
        t = t[: limit - 1].rstrip() + "…"
    return t


def strip_md(text):
    """Remove the markup that would otherwise be indexed as words."""
    t = text
    t = re.sub(r"`([^`]*)`", r"\1", t)
    t = re.sub(r"\*\*([^*]*)\*\*", r"\1", t)
    t = re.sub(r"\*([^*]*)\*", r"\1", t)
    t = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", t)
    t = t.replace(">", " ")
    return t


def github_slug(heading):
    """GitHub's heading anchor algorithm, for `#`-headings only."""
    s = unicodedata.normalize("NFKD", heading)
    s = strip_md(s).strip().lower()
    s = re.sub(r"[^\w\s-]", "", s, flags=re.UNICODE)
    s = re.sub(r"\s+", "-", s)
    return s


DATE_RE = re.compile(r"(\d{4}-\d{2}-\d{2})")


def find_date(text):
    m = DATE_RE.search(text)
    return m.group(1) if m else None


def paragraphs(block_lines, start_line):
    """Split a run of lines into (start_line_number, [lines]) paragraphs.

    A paragraph boundary is a blank line. This is the discriminator that keeps a
    wrapped `**word**` mid-sentence from being read as a bold-lead heading —
    CLAUDE.md:141 is exactly that case.
    """
    out = []
    cur = []
    cur_start = start_line
    for i, ln in enumerate(block_lines):
        if ln.strip() == "":
            if cur:
                out.append((cur_start, cur))
                cur = []
            cur_start = start_line + i + 1
        else:
            if not cur:
                cur_start = start_line + i
            cur.append(ln)
    if cur:
        out.append((cur_start, cur))
    return out


def bold_lead_title(par_lines):
    """Return (title, rest) for a paragraph opening with `**`, else (None, None).

    The bold run may span several wrapped lines — `**27d — THE FIFTH SIGNATURE IS
    NAMED FORWARD: dark desaturated crevice` closes on the following line — so the
    closing `**` is searched across the whole paragraph.
    """
    text = "\n".join(par_lines)
    if not text.startswith("**"):
        return None, None
    end = text.find("**", 2)
    if end < 0:
        return None, None
    return text[2:end], text[end + 2:]


# ---------------------------------------------------------------------------
# parsers — one per convention
# ---------------------------------------------------------------------------

RULING_HDR = re.compile(r"^## Ruling (\d+)\b(.*)$")
ADDENDA_HDR = re.compile(r"^## Post-ingest addenda\s*(\d*)\b(.*)$")
AMEND_HDR = re.compile(r"^> ### (?:⚠\s*)?Amendment (\d+) \((.*)$")

# MEASURED, not assumed: across all five ruling documents the lettered marker is
# `**<n><letter> <dash>` — letter, SPACE, dash — 151 times out of 152. The single
# exception is not a sub-ruling at all but a CLOSURE marker naming the sub-ruling
# it closes (`**18g-CLOSED (Director, 2026-08-06): "Keep ivory, judge on asset."`),
# and it carries the Director's own sentence. A dash class that tolerates a bare
# hyphen swallows it into 18g and loses one of the two holdings. So the space is
# required, and the suffixed form gets its own pattern and its own row.
SUB_RULING = re.compile(r"^\*\*(\d+)([a-z])\s+" + DASH)
SUB_CLOSURE = re.compile(r"^\*\*(\d+)([a-z])-([A-Z][A-Z-]+)\b")
HANDOFF_HDR = re.compile(r"^## Session handoff\s*(\d*)\s*\((.*)$")
SECTION_HDR = re.compile(r"^(#{2,3}) +(.*)$")

# correction / supersession verbs, directed at a numbered ruling. Conservative by
# design: a phrase this does not match is under-counted, never mis-attributed.
SUPERSEDE_RE = re.compile(
    r"(?:Ruling|Amendment)\s+(\d+[a-z]?)(?:'s [^.;:]{0,60}?)?\s+"
    r"(?:is\s+|are\s+)?(?:now\s+)?"
    r"(?:CORRECTED|corrected|WITHDRAWN|withdrawn|SUPERSEDED|superseded|VOID|void)\b"
)
SUPERSEDE_TITLE_RE = re.compile(
    r"\b(\d+[a-z]?)\s+(?:is\s+)?(?:corrected in place|CORRECTED IN PLACE|withdrawn|WITHDRAWN)"
)


def parse_rulings():
    """Numbered rulings, their lettered sub-rulings, amendments and addenda."""
    rows = []
    for arc, rel in NUMBERED_RULING_FILES:
        rows.extend(_parse_numbered(arc, rel, RULING_HDR, "ruling", "Ruling"))
        rows.extend(_parse_numbered(arc, rel, ADDENDA_HDR, "addendum", "Post-ingest addenda"))
    for arc, rel in AMENDMENT_FILES:
        rows.extend(_parse_amendments(arc, rel))
    rows.sort(key=lambda r: (r["arc"], r["sort_num"], r["sort_letter"], r["kind"]))
    return rows


def _header_blocks(ls, pattern):
    """Yield (match, header_line_no, body_lines) for every header match."""
    hits = [(i, pattern.match(ln)) for i, ln in enumerate(ls)]
    hits = [(i, m) for i, m in hits if m]
    for k, (i, m) in enumerate(hits):
        end = hits[k + 1][0] if k + 1 < len(hits) else len(ls)
        # a later `## ` header of another kind also terminates the block
        for j in range(i + 1, end):
            if ls[j].startswith("## "):
                end = j
                break
        yield m, i, ls[i + 1:end]


def _parse_numbered(arc, rel, pattern, kind, label):
    out = []
    ls = lines_of(rel)
    for m, i, body in _header_blocks(ls, pattern):
        num = m.group(1)
        if not num:
            num = "1"          # E11's first addendum carries no digit
        tail = m.group(2)
        title = re.sub(r"^\s*" + DASH + r"\s*", "", tail).strip()
        title = re.sub(r"^\(([^)]*)\)\s*" + DASH + r"\s*", "", title).strip()
        anchor = "%s %s" % (label, num)
        subs = _parse_subs(arc, rel, num, kind, body, i + 1, find_date(m.group(0)))
        # A parent's body must NOT re-index its sub-rulings' prose: every sub is its
        # own row, so including their text made Ruling 4 a 3,932-character document
        # that competes with its own five children and dilutes bm25's length
        # normalisation for both. The parent keeps only what belongs to it.
        own = _minus_sub_paragraphs(body, i + 1, subs)
        row = dict(
            arc=arc, number=num, parent=None, kind=kind,
            date=find_date(m.group(0)) or find_date("\n".join(body[:6])),
            holding=one_line(strip_md(title)) or one_line(strip_md(tail)),
            body=strip_md(own),
            file=rel, anchor=anchor, locator=ls[i].rstrip(), line=i + 1,
            sort_num=int(num), sort_letter="",
        )
        out.append(row)
        out.extend(subs)
    return out


def _minus_sub_paragraphs(body, body_start, subs):
    """The parent's own prose: the block minus every paragraph a sub-ruling owns."""
    owned = set()
    for s in subs:
        first = s["line"] - 1 - body_start
        n = len(s["body"].split("\n"))
        for k in range(first, first + n + 1):
            owned.add(k)
    return "\n".join(ln for k, ln in enumerate(body) if k not in owned)


SKIPPED_CROSSREFS = []


def _parse_subs(arc, rel, parent_num, parent_kind, body, body_start, parent_date):
    """Lettered sub-rulings — and closure markers — inside one ruling's body."""
    out = []
    pars = paragraphs(body, body_start)
    for start, par in pars:
        first = par[0]
        m = SUB_RULING.match(first)
        closure = None if m else SUB_CLOSURE.match(first)
        if not m and not closure:
            continue
        g = m or closure
        num, letter = g.group(1), g.group(2)
        if num != parent_num:
            # a lettered marker numbered for a DIFFERENT ruling is a cross-reference
            # opening a paragraph, not this ruling's own sub-ruling. Skipped, and
            # recorded so the report can quote how often it happens.
            SKIPPED_CROSSREFS.append((rel, start + 1, first[:70]))
            continue
        title, rest = bold_lead_title(par)
        if title is None:
            continue
        if closure:
            suffix = "-" + g.group(3)
            number = num + letter + suffix
            anchor = "Ruling %s%s%s" % (num, letter, suffix)
            locator = "**%s%s%s" % (num, letter, suffix)
            kind = "sub-%s-closure" % parent_kind
            title = re.sub(r"^\d+[a-z]-[A-Z-]+\s*:?\s*", "", title)
        else:
            number = num + letter
            anchor = "Ruling %s%s" % (num, letter)
            locator = "**%s%s " % (num, letter)
            kind = "sub-" + parent_kind
            title = re.sub(r"^\d+[a-z]\s*" + DASH + r"\s*", "", title)
        out.append(dict(
            arc=arc, number=number, parent=num, kind=kind,
            date=find_date(g.group(0)) or find_date(title) or parent_date,
            holding=one_line(strip_md(title)),
            body=strip_md("\n".join(par)),
            file=rel, anchor=anchor, locator=locator, line=start + 1,
            sort_num=int(num), sort_letter=letter,
        ))
    return out


def _parse_amendments(arc, rel):
    out = []
    ls = lines_of(rel)
    for m, i, body in _header_blocks(ls, AMEND_HDR):
        num = m.group(1)
        tail = m.group(2)
        author = tail.split(")")[0]
        title = tail.split(")", 1)[1] if ")" in tail else tail
        title = re.sub(r"^\s*" + DASH + r"\s*", "", title).strip()
        out.append(dict(
            arc=arc, number="A" + num, parent=None, kind="amendment",
            date=find_date(author),
            holding=one_line(strip_md(title)),
            body=strip_md("\n".join(body)),
            file=rel, anchor="Amendment %s" % num,
            locator="Amendment %s (" % num, line=i + 1,
            sort_num=int(num), sort_letter="",
        ))
    return out


# The record announces its verdicts in capitals and names its authority in the
# header. Both are ontology this index was missing: without them, the ruling that IS
# an acceptance is indistinguishable from the three that merely discuss one, and
# "when was the pair accepted" ranks the discussion above the event. Ordered most-
# to least specific; the first hit in the holding wins.
VERDICTS = [
    "ACCEPTED", "REJECTED", "RATIFIED", "WITHDRAWN", "FALSIFIED", "CONFIRMED",
    "DESIGNATED", "DIRECTED", "ADOPTED", "SUSPENDED", "RELEASED", "CLOSED",
    "CLEARED", "HALTED", "BANKED", "MINTED", "VOID", "RULED",
]


def classify(holding):
    """(verdict, authority) for a ruling, from the record's own capitalised marks.

    THE CAPITALS ARE THE CONVENTION AND MUST NOT BE NORMALISED AWAY. A verdict is
    what a ruling DOES, and the record shouts it: `THE PAIR IS ACCEPTED`,
    `the pair is REJECTED`, `is RATIFIED end to end`, `GATE 1: ACCEPTED`. The same
    word in lower case is an adjective describing an artifact — `D9's wine has no
    cluster on the accepted pair` is not an acceptance. An earlier version of this
    function upper-cased the holding first and so marked three rulings ACCEPTED that
    accept nothing, which put two of them above the actual acceptance in the ranking.
    Match case-sensitively.
    """
    verdict = None
    for v in VERDICTS:
        if re.search(r"\b%s\b" % v, holding):
            verdict = v
            break
    authority = "Director" if re.search(r"\bDirector\b", holding) else "advisor"
    return verdict, authority


def link_supersessions(rulings):
    """Populate supersedes / superseded_by from EXPLICIT correction verbs only.

    A lower bound by construction: the record also corrects by narrative ("the
    word stands, anchored by…"), which no pattern reads without guessing. The
    report states the coverage rather than implying completeness.
    """
    by_key = {}
    for r in rulings:
        by_key[(r["arc"], r["number"])] = r
        r["supersedes"] = []
        r["superseded_by"] = []
    for r in rulings:
        hay = r["holding"] + " \n " + r["body"][:4000]
        targets = set(SUPERSEDE_RE.findall(hay)) | set(SUPERSEDE_TITLE_RE.findall(r["holding"]))
        for t in sorted(targets):
            if t == r["number"]:
                continue
            tgt = by_key.get((r["arc"], t))
            if tgt is None:
                continue
            if t not in r["supersedes"]:
                r["supersedes"].append(t)
            if r["number"] not in tgt["superseded_by"]:
                tgt["superseded_by"].append(r["number"])
    for r in rulings:
        r["supersedes"] = ",".join(sorted(r["supersedes"])) or None
        r["superseded_by"] = ",".join(sorted(r["superseded_by"])) or None


NUM_RULE = re.compile(r"^(\d+)\. +\*\*")
LIST_ITEM = re.compile(r"^(?:\d+\.|[-*]) +")
PAID_RE = re.compile(r"\b(E0[1-9]|E1[0-5])\b")


LIST_LAW = re.compile(r"^(?:\d+\.|[-*]) +\*\*")


def list_items(par):
    """Split a paragraph wherever a list item OPENS IN BOLD — the law shape.

    Two properties of CLAUDE.md make a plain blank-line splitter lose most of the
    corpus, and both were measured rather than assumed:

      * lists carry NO blank line between items, so ten numbered role rules read as
        one block and only the first is captured (2 of 10 before this existed, with
        the four `Judging artifacts` and eight `Standing technical constraints`
        bullets absent entirely);
      * an item may itself CONTAIN a blank line — advisor rule 3 runs to two
        paragraphs — after which items 4 and 5 sit in a block that no longer starts
        with a marker, and were lost even once list splitting existed.

    So the split is on the marker-plus-bold pattern anywhere in the block, not on the
    block's first line. Requiring the `**` immediately after the marker keeps prose
    that merely begins a line with `- ` from being cut into phantom laws.
    """
    if not any(LIST_LAW.match(ln) for ln in par):
        return [par]
    out, cur = [], []
    for ln in par:
        if LIST_LAW.match(ln) and cur:
            out.append(cur)
            cur = [ln]
        else:
            cur.append(ln)
    if cur:
        out.append(cur)
    return out


def parse_laws():
    """The CLAUDE.md law corpus.

    Three forms, all the file's own: bold-lead paragraphs (`**An inherited claim
    is…**`), numbered role rules (`1. **Never judge…**`) and bulleted constraints
    (`- **Weld before decimating.**`). A law must open its paragraph OR its list
    item — which is what keeps a wrapped mid-sentence `**word**` (CLAUDE.md:141) out
    of the table, while still reaching the items inside a blank-line-free list.
    """
    rows = []
    for rel in LAW_FILES:
        ls = lines_of(rel)
        heads = [(i, ln) for i, ln in enumerate(ls) if ln.startswith("## ")]
        bounds = []
        for k, (i, ln) in enumerate(heads):
            end = heads[k + 1][0] if k + 1 < len(heads) else len(ls)
            bounds.append((ln[3:].strip(), i, end))
        for section, s, e in bounds:
            for start, block in paragraphs(ls[s + 1:e], s + 1):
                offset = 0
                for par in list_items(block):
                    line = start + offset
                    offset += len(par)
                    first = par[0]
                    title, kind = None, None
                    if BOLD_LEAD.match(first):
                        title, _ = bold_lead_title(par)
                        kind = "law"
                    elif LIST_ITEM.match(first):
                        inner = "\n".join(par).split("**", 2)
                        # the bold must open the item: anything between the marker
                        # and the `**` means the bold is mid-sentence, not a statement
                        if len(inner) >= 3 and not LIST_ITEM.sub("", inner[0]).strip():
                            title = inner[1]
                            kind = "rule" if NUM_RULE.match(first) else "law"
                    if title is None:
                        continue
                    stmt = one_line(strip_md(title))
                    if len(stmt) < 12:
                        continue
                    body = strip_md("\n".join(par))
                    paid = sorted(set(PAID_RE.findall(body)))
                    rows.append(dict(
                        statement=stmt, kind=kind, section=section,
                        paid_for_by=",".join(paid) or None, body=body, file=rel,
                        anchor="%s · %s" % (section, stmt[:60]),
                        locator=first.rstrip(), line=line + 1,
                    ))
    return rows


EXP_ROW = re.compile(r"^\| \[?(E\d\d)\]?(?:\([^)]*\))? \| (.*?) \| (.*?) \|\s*$")


def parse_experiments():
    """E01…, from the experiments README table, supplemented by the filesystem.

    The table is the authored source; it is also STALE by construction (E13/E14/E15
    have no row, E12's row says "Rulings 1-8"). Experiments present on disk but
    absent from the table enter with status `not in the README table` — a reported
    finding, never a silent fill.
    """
    rows = {}
    rel = "docs/experiments/README.md"
    for ln in lines_of(rel):
        m = EXP_ROW.match(ln)
        if not m:
            continue
        eid, question, status = m.group(1), m.group(2), m.group(3)
        rows[eid] = dict(
            id=eid, question=one_line(strip_md(question), 400),
            status=one_line(strip_md(status), 400),
            verdict=_verdict(status), spec_file=None, report_file=None,
            body=strip_md(question + " " + status),
            file=rel, anchor="the experiment table · %s" % eid,
            locator="| [%s]" % eid, line=0,
        )
    # locate each experiment's own files, and discover experiments the table omits
    # .md first, then the rest, each alphabetically — so an experiment discovered
    # from disk is anchored at a document's heading rather than at a JSON's `{`.
    files = sorted(
        (f for f in os.listdir(os.path.join(REPO, "docs/experiments"))
         if re.match(r"^E\d\d[-.]", f)),
        key=lambda f: (0 if f.endswith(".md") else 1, f))
    for f in files:
        eid = f[:3]
        r = rows.get(eid)
        if r is None:
            # E13/E14/E15 have no README-table row. They enter from disk, pointed at
            # their own document's first heading — a locator findable IN that file,
            # rather than the filename, which is not text inside it. The missing
            # table row is a reported finding; this parser does not write one.
            rel_f = "docs/experiments/" + f
            head, head_line = _first_heading(rel_f)
            r = rows[eid] = dict(
                id=eid, question=None,
                status="not in the README table",
                verdict=None, spec_file=None, report_file=None, body="",
                file=rel_f,
                anchor="files on disk · %s" % eid,
                locator=head, line=head_line,
            )
        rp = "docs/experiments/" + f
        if r["spec_file"] is None and re.search(r"(kickoff|spec|-E\d|-the-|-cover-|-paint-|-cull-|-atlas-|-facial-|-texture-|-environment-|-dense-|-context-)", f):
            r["spec_file"] = rp
        if r["report_file"] is None and "report" in f:
            r["report_file"] = rp
    for eid, r in rows.items():
        if r["locator"] == "| [%s]" % eid and r["line"] == 0:
            for i, ln in enumerate(lines_of(rel)):
                if ln.startswith("| [%s]" % eid) or ln.startswith("| %s " % eid):
                    r["line"] = i + 1
                    r["locator"] = ln[:40].rstrip()
                    break
    return [rows[k] for k in sorted(rows)]


def _first_heading(rel):
    """First `#` heading of a file, and its 1-based line. Falls back to line 1."""
    ls = lines_of(rel)
    for i, ln in enumerate(ls):
        if ln.startswith("#"):
            return ln.rstrip(), i + 1
    for i, ln in enumerate(ls):
        if ln.strip():
            return ln.rstrip()[:60], i + 1
    return "", 1


def _verdict(status):
    s = status.upper()
    for word in ("ACCEPTED", "RULED", "IN FLIGHT", "RUN AND RULED", "STAGED", "CLOSED"):
        if word in s:
            return word
    return None


def parse_handoffs():
    """Executor dispatches and halts, arc-scoped because the numbers collide.

    E04's first handoff carries no number at all (`## Session handoff (2026-08-04,
    evening) — … SUPERSEDED`). It is recorded as number `1` with its unnumbered form
    kept in the locator, because dropping a real dispatch to satisfy a regex would
    lose a row the count check is entitled to see.
    """
    rows = []
    for arc, rel in HANDOFF_FILES:
        ls = lines_of(rel)
        for m, i, body in _header_blocks(ls, HANDOFF_HDR):
            num = m.group(1) or "1"
            tail = m.group(2)
            date = find_date(tail)
            title = tail.split(")", 1)[1] if ")" in tail else tail
            title = re.sub(r"^\s*" + DASH + r"\s*", "", title).strip()
            txt = "\n".join(body)
            rows.append(dict(
                arc=arc, number=int(num), date=date,
                outcome=one_line(strip_md(title), 300),
                commits=",".join(sorted(set(re.findall(r"`([0-9a-f]{7,40})`", txt)))) or None,
                superseded=1 if "SUPERSEDED" in ls[i] else 0,
                body=strip_md(txt),
                file=rel, anchor="Session handoff %s (%s)" % (num, arc),
                locator=ls[i].rstrip()[:60], line=i + 1,
            ))
    rows.sort(key=lambda r: (r["arc"], r["number"]))
    return rows


def parse_decisions():
    """An INDEX over the profiles' registry. The profile stays canonical.

    Only `{value, why, from}` entries are indexed — the shape `subject_profile.bind`
    enforces. Keys beginning `_` are the profiles' own meta/marker convention and are
    recorded as status markers rather than as decided values.
    """
    rows = []
    for rel in PROFILE_FILES:
        prof = json.loads(read(rel))
        subject = prof.get("name") or os.path.basename(rel)
        text = read(rel).split("\n")
        # `_still_suspended` is where undecidedness actually lives — and each entry
        # opens with its own disposition (RESOLVED / RULED / DECIDED / CONVERTED /
        # PARTIALLY SUPERSEDED / DERIVED, AWAITING …), so the block is a history of
        # what was suspended and how it closed. Indexed under the pseudo-tool
        # `_still_suspended` so a session can ask what a subject still owes.
        for key in sorted(prof.get("_still_suspended", {})):
            note = str(prof["_still_suspended"][key])
            rows.append(dict(
                subject=subject, tool="_still_suspended", key=key,
                value=one_line(note, 200), status=_decision_status(note),
                ruling=None, why=one_line(note, 400),
                body=strip_md("%s %s" % (key, note)),
                file=rel, anchor="%s · _still_suspended · %s" % (subject, key),
                locator='"%s"' % key, line=_line_of(text, '"%s"' % key),
            ))
        for tool in sorted(prof.get("tools", {})):
            block = prof["tools"][tool]
            for key in sorted(block):
                ent = block[key]
                if key.startswith("_"):
                    rows.append(dict(
                        subject=subject, tool=tool, key=key,
                        value=one_line(str(ent), 200), status="marker",
                        ruling=None, why=None,
                        body=strip_md("%s %s" % (key, ent)),
                        file=rel, anchor="%s · %s · %s" % (subject, tool, key),
                        locator='"%s"' % key, line=_line_of(text, '"%s"' % key),
                    ))
                    continue
                if not isinstance(ent, dict) or "value" not in ent:
                    continue
                why = ent.get("why", "")
                rows.append(dict(
                    subject=subject, tool=tool, key=key,
                    value=one_line(json.dumps(ent["value"], ensure_ascii=False), 200),
                    status=_decision_status(why),
                    ruling=ent.get("from"),
                    why=one_line(why, 400),
                    body=strip_md("%s %s %s %s" % (key, ent["value"], why, ent.get("from", ""))),
                    file=rel, anchor="%s · %s · %s" % (subject, tool, key),
                    locator='"%s"' % key, line=_line_of(text, '"%s"' % key),
                ))
    return rows


CLASS_LABEL = re.compile(r"^([A-Z][A-Z0-9 /_-]{3,44})(?=[:,.(—-]|\s+-\s)")


def _decision_status(why):
    """The entry's class, read ONLY from a capitalised label at the head of `why`.

    That leading label is the profiles' own convention — `FIRST-RUN OPERATING POINT
    at the accepted route's value`, `PROTECTIVE TRANSCRIPTION (the E04 Ruling 22
    class)`, `SPENT, WITH A BYTE ANCHOR`. Anywhere ELSE in the prose the same words
    are narrative about the past, and reading them as status inverts their meaning:
    an earlier version scanned the whole string and so labelled three entries
    UNDECIDED whose `why` says *"the arc's one deliberately undecided value"* (ruled
    0.005 by E12 Ruling 25c) and *"Found undecided by Ruling 25's sweep, then
    anchored"*. An index that reports a decided value as undecided is a second
    authority contradicting the record, which is the one thing this design forbids.

    An entry that carries a `value` at all is DECIDED by the loader's own semantics —
    `subject_profile.bind` applies it to the tool. Undecidedness lives in the
    `_still_suspended` block and the `_`-prefixed markers, both indexed separately.
    """
    m = CLASS_LABEL.match(why.strip())
    if m:
        label = m.group(1).strip()
        if len(label.split()) <= 6:
            return label
    return "decided"


def _line_of(text_lines, needle):
    for i, ln in enumerate(text_lines):
        if needle in ln:
            return i + 1
    return 0


# The record writes Windows paths with BACKSLASHES (`facet_E02\out\atlas_final.png`)
# and shell fragments with variable prefixes (`"$j\inpainted.png"`). Both are matched;
# `$` and `%` are excluded from the lookbehind so a variable prefix is not swallowed
# into the path (which would mint a phantom artifact called `j/inpainted.png`).
ARTIFACT_RE = re.compile(
    r"(?<![\w/\\.$%-])((?:[A-Za-z0-9_][A-Za-z0-9_.\-]*[/\\])*[A-Za-z0-9_][A-Za-z0-9_.\-]*"
    r"\.(?:glb|png|npy|jsonl|json|obj|ply|ps1|sh))(?![\w])"
)
STATUS_WORDS = [
    ("ACCEPTED", r"\bACCEPTED\b"),
    ("REJECTED", r"\bREJECTED\b"),
    ("SUPERSEDED", r"\bSUPERSEDED\b|\bsuperseded\b"),
    ("WITHDRAWN", r"\bWITHDRAWN\b|\bwithdrawn\b"),
    ("FROZEN", r"\bfrozen as canon\b|\bFROZEN\b"),
]
# extensions that are the record's own instruments/inputs rather than artifacts
ARTIFACT_KIND = {
    "glb": "mesh", "png": "render", "npy": "array", "json": "data",
    "jsonl": "log", "obj": "mesh", "ply": "mesh", "ps1": "script", "sh": "script",
}


def parse_artifacts(ruling_index):
    """Meshes, renders, sidecars and sheets, extracted by path shape.

    THE RECORD HAS NO CONVENTION FOR THESE. They are paths in prose. So this is
    extraction, not parsing: every path-shaped token in the markdown record becomes a
    row carrying where it is mentioned, how often, and — only where a status word
    stands in the same paragraph — a status. Absent that, status is NULL rather than
    guessed. `provenance_ruling` is the nearest preceding ruling anchor in the same
    file, which is a locality heuristic and is labelled as one.
    """
    seen = {}
    for rel in record_markdown():
        ls = lines_of(rel)
        pars = paragraphs(ls, 0)
        for start, par in pars:
            text = "\n".join(par)
            status = None
            for name, pat in STATUS_WORDS:
                if re.search(pat, text):
                    status = name
                    break
            for m in ARTIFACT_RE.finditer(text):
                raw = m.group(1)
                # the KEY is separator-normalised, because `facet_E02\out\x.png` and
                # `facet_E02/out/x.png` are one artifact; the LOCATOR stays raw,
                # because the pointer gate looks for it in the file as written.
                tok = raw.replace("\\", "/")
                if tok.count(".") and tok.split(".")[-1] not in ARTIFACT_KIND:
                    continue
                rec = seen.get(tok)
                if rec is None:
                    rec = seen[tok] = dict(
                        path=tok, kind=ARTIFACT_KIND[tok.split(".")[-1]],
                        status=status, mentions=0,
                        provenance_ruling=_nearest_ruling(ruling_index, rel, start + 1),
                        body="", file=rel, anchor="first mentioned in %s" % rel,
                        locator=raw, line=start + 1,
                    )
                rec["mentions"] += 1
                if rec["status"] is None and status is not None:
                    rec["status"] = status
                if len(rec["body"]) < 1200:
                    rec["body"] = (rec["body"] + " " + one_line(strip_md(text), 400)).strip()
    return [seen[k] for k in sorted(seen)]


def _nearest_ruling(ruling_index, rel, line):
    best = None
    for r in ruling_index:
        if r["file"] != rel or r["line"] > line:
            continue
        if best is None or r["line"] > best["line"]:
            best = r
    return best["anchor"] if best else None


# the record's own naming verbs. A phenomenon in this repo is minted out loud.
PHENOM_PATTERNS = [
    ("banked as a measured phenomenon", r"is BANKED as a measured phenomenon"),
    ("minted", r"IS MINTED|is MINTED"),
    ("named forward", r"IS NAMED FORWARD"),
    ("named", r"\bis NAMED\b|\bIS NAMED\b|\bis named:|\bclass is named\b"),
    ("ledger form", r"the ledger takes the form, named"),
    ("new law", r"a new law for the record"),
    ("banked as", r"\bis BANKED as\b|\bis banked as (?:a|the|this)\b"),
]


def parse_phenomena(rulings):
    """The named measured effects.

    ALSO CONVENTIONLESS, and named with at least seven different verbs. This reads
    the verbs the record actually uses and reports what that catches. A phenomenon
    named without one of them is invisible here, and that is the honest boundary of
    the table rather than a bug to paper over with a hand-kept list — a hand-kept
    list is exactly what the design forbids.
    """
    rows = []
    for r in rulings:
        text = r["holding"] + "\n" + r["body"]
        hit = None
        for name, pat in PHENOM_PATTERNS:
            if re.search(pat, text):
                hit = name
                break
        if hit is None:
            continue
        rows.append(dict(
            name=one_line(r["holding"], 140),
            marker=hit,
            statement=one_line(r["holding"], 300),
            instances=r["arc"],
            body=r["body"][:4000],
            file=r["file"], anchor=r["anchor"], locator=r["locator"], line=r["line"],
        ))
    rows.sort(key=lambda x: (x["file"], x["line"]))
    return rows


def parse_prose():
    """Every prose section of the record that no structured table already owns.

    The reports, predictions, halts, specs and kickoffs are where the MEASUREMENTS
    live — a ruling cites them, and a session that can find the ruling but not the
    evidence has half an index. So the whole `docs/experiments/` markdown corpus is
    sectioned by heading here, alongside README, the handbook and the design docs.

    Sections a structured table already owns are skipped so a holding is not indexed
    twice under two identities: `## Ruling N`, `## Post-ingest addenda N` and
    `## Session handoff N` blocks belong to `rulings` and `handoffs`. The E08
    amendments sit inside a blockquote under `## 3.`, so that document is excluded
    from prose wholesale and reached through its amendment rows.
    """
    owned_hdr = (RULING_HDR, ADDENDA_HDR, HANDOFF_HDR)
    structured = {rel for _, rel in NUMBERED_RULING_FILES}
    structured |= {rel for _, rel in AMENDMENT_FILES}
    files = list(PROSE_FILES)
    files += [rel for _, rel in TOPICAL_RULING_FILES]
    files += [rel for _, rel in HANDOFF_FILES]
    files += [f for f in record_markdown()
              if f.startswith("docs/experiments/") and f not in files]
    rows = []
    for rel in sorted(set(files)):
        if rel in structured:
            continue
        ls = lines_of(rel)
        heads = [(i, m) for i, m in ((i, SECTION_HDR.match(ln)) for i, ln in enumerate(ls)) if m]
        if not heads:
            # a document with no `##` heading is still evidence; index it whole
            body = strip_md("\n".join(ls))
            if len(body.strip()) < 40:
                continue
            head, hl = _first_heading(rel)
            rows.append(dict(title=one_line(strip_md(head).lstrip("# "), 200),
                             body=body, file=rel, anchor="(whole document)",
                             locator=head, line=hl))
            continue
        # a `##` block owned by a structured table owns its `###` children too —
        # otherwise a handoff's task list is indexed twice, once as part of the
        # handoff row and once on its own, and the two compete in the ranking.
        owned_spans = []
        h2 = [i for i, _ in heads if ls[i].startswith("## ")]
        for k, i in enumerate(h2):
            if any(h.match(ls[i]) for h in owned_hdr):
                owned_spans.append((i, h2[k + 1] if k + 1 < len(h2) else len(ls)))

        def is_owned(line_no):
            return any(a <= line_no < b for a, b in owned_spans)

        # the preamble above the first `##` carries the document's own thesis
        pre = strip_md("\n".join(ls[:heads[0][0]]))
        if len(pre.strip()) >= 40:
            head, hl = _first_heading(rel)
            rows.append(dict(title=one_line(strip_md(head).lstrip("# "), 200),
                             body=pre, file=rel, anchor="(preamble)",
                             locator=head, line=hl))
        for k, (i, m) in enumerate(heads):
            end = heads[k + 1][0] if k + 1 < len(heads) else len(ls)
            if is_owned(i):
                continue
            title = strip_md(m.group(2)).strip()
            body = strip_md("\n".join(ls[i + 1:end]))
            if len(body.strip()) < 40:
                continue
            rows.append(dict(
                title=one_line(title, 200), body=body,
                file=rel, anchor=title[:80], locator=ls[i].rstrip()[:70], line=i + 1,
            ))
    rows.sort(key=lambda r: (r["file"], r["line"]))
    return rows


# ---------------------------------------------------------------------------
# build
# ---------------------------------------------------------------------------

SCHEMA = """
CREATE TABLE rulings (
  arc TEXT NOT NULL, number TEXT NOT NULL, parent TEXT, kind TEXT NOT NULL,
  date TEXT, verdict TEXT, authority TEXT NOT NULL,
  holding TEXT NOT NULL, file TEXT NOT NULL, anchor TEXT NOT NULL,
  locator TEXT NOT NULL, line INTEGER NOT NULL,
  supersedes TEXT, superseded_by TEXT,
  PRIMARY KEY (arc, number, kind)
) WITHOUT ROWID;

CREATE TABLE laws (
  statement TEXT NOT NULL, kind TEXT NOT NULL, section TEXT, paid_for_by TEXT,
  file TEXT NOT NULL, anchor TEXT NOT NULL, locator TEXT NOT NULL,
  line INTEGER NOT NULL
);

CREATE TABLE experiments (
  id TEXT PRIMARY KEY, question TEXT, status TEXT, verdict TEXT,
  spec_file TEXT, report_file TEXT,
  file TEXT NOT NULL, anchor TEXT NOT NULL, locator TEXT NOT NULL,
  line INTEGER NOT NULL
) WITHOUT ROWID;

CREATE TABLE handoffs (
  arc TEXT NOT NULL, number INTEGER NOT NULL, date TEXT, outcome TEXT,
  commits TEXT, superseded INTEGER NOT NULL,
  file TEXT NOT NULL, anchor TEXT NOT NULL, locator TEXT NOT NULL,
  line INTEGER NOT NULL,
  PRIMARY KEY (arc, number)
) WITHOUT ROWID;

CREATE TABLE artifacts (
  path TEXT PRIMARY KEY, kind TEXT NOT NULL, status TEXT, mentions INTEGER NOT NULL,
  provenance_ruling TEXT,
  file TEXT NOT NULL, anchor TEXT NOT NULL, locator TEXT NOT NULL,
  line INTEGER NOT NULL
) WITHOUT ROWID;

CREATE TABLE phenomena (
  name TEXT NOT NULL, marker TEXT NOT NULL, statement TEXT NOT NULL,
  instances TEXT,
  file TEXT NOT NULL, anchor TEXT NOT NULL, locator TEXT NOT NULL,
  line INTEGER NOT NULL
);

CREATE TABLE decisions (
  subject TEXT NOT NULL, tool TEXT NOT NULL, key TEXT NOT NULL,
  value TEXT, status TEXT NOT NULL, ruling TEXT, why TEXT,
  file TEXT NOT NULL, anchor TEXT NOT NULL, locator TEXT NOT NULL,
  line INTEGER NOT NULL,
  PRIMARY KEY (subject, tool, key)
) WITHOUT ROWID;

-- `title` is the SEARCH surface: a concatenation tuned for retrieval (arc, anchor,
-- authority, verdict, holding). `disp` is what a reader sees — the row's own
-- one-line holding. They are separate because optimising one degrades the other:
-- a search title packed with arc and verdict tokens reads as noise in a result list.
CREATE VIRTUAL TABLE fts USING fts5(
  title, body,
  tbl UNINDEXED, key UNINDEXED, file UNINDEXED, anchor UNINDEXED,
  locator UNINDEXED, line UNINDEXED, disp UNINDEXED,
  tokenize = 'unicode61 remove_diacritics 2'
);
"""


def build(db_path, quiet=False):
    rulings = parse_rulings()
    link_supersessions(rulings)
    laws = parse_laws()
    experiments = parse_experiments()
    handoffs = parse_handoffs()
    decisions = parse_decisions()
    artifacts = parse_artifacts(rulings)
    phenomena = parse_phenomena(rulings)
    prose = parse_prose()

    d = os.path.dirname(db_path)
    if d and not os.path.isdir(d):
        os.makedirs(d)          # scripts create their own output directories
    if os.path.exists(db_path):
        os.remove(db_path)      # fresh DB each build; never an incremental update

    con = sqlite3.connect(db_path)
    con.execute("PRAGMA page_size=4096")
    con.execute("PRAGMA journal_mode=DELETE")
    con.executescript(SCHEMA)
    fts = []

    def add_fts(tbl, key, title, body, file, anchor, locator, line, disp=None):
        fts.append((title or "", body or "", tbl, key, file, anchor, locator, line,
                    disp if disp is not None else (title or "")))

    with con:
        for r in rulings:
            verdict, authority = classify(r["holding"])
            con.execute(
                "INSERT INTO rulings VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
                (r["arc"], r["number"], r["parent"], r["kind"], r["date"],
                 verdict, authority, r["holding"],
                 r["file"], r["anchor"], r["locator"], r["line"],
                 r["supersedes"], r["superseded_by"]))
            add_fts("rulings", "%s %s" % (r["arc"], r["anchor"]),
                    "%s %s %s %s %s" % (r["arc"], r["anchor"], authority,
                                        verdict or "", r["holding"]),
                    r["body"], r["file"], r["anchor"], r["locator"], r["line"],
                    disp=r["holding"])
        for r in laws:
            con.execute("INSERT INTO laws VALUES (?,?,?,?,?,?,?,?)",
                        (r["statement"], r["kind"], r["section"], r["paid_for_by"],
                         r["file"], r["anchor"], r["locator"], r["line"]))
            add_fts("laws", r["statement"][:60], r["statement"], r["body"],
                    r["file"], r["anchor"], r["locator"], r["line"],
                    disp=r["statement"])
        for r in experiments:
            con.execute("INSERT INTO experiments VALUES (?,?,?,?,?,?,?,?,?,?)",
                        (r["id"], r["question"], r["status"], r["verdict"],
                         r["spec_file"], r["report_file"],
                         r["file"], r["anchor"], r["locator"], r["line"]))
            add_fts("experiments", r["id"], "%s %s" % (r["id"], r["question"] or ""),
                    r["body"], r["file"], r["anchor"], r["locator"], r["line"],
                    disp=r["question"] or r["status"])
        for r in handoffs:
            con.execute("INSERT INTO handoffs VALUES (?,?,?,?,?,?,?,?,?,?)",
                        (r["arc"], r["number"], r["date"], r["outcome"], r["commits"],
                         r["superseded"], r["file"], r["anchor"], r["locator"], r["line"]))
            add_fts("handoffs", "%s handoff %d" % (r["arc"], r["number"]),
                    "%s handoff %d %s" % (r["arc"], r["number"], r["outcome"]),
                    r["body"], r["file"], r["anchor"], r["locator"], r["line"],
                    disp=r["outcome"])
        for r in artifacts:
            con.execute("INSERT INTO artifacts VALUES (?,?,?,?,?,?,?,?,?)",
                        (r["path"], r["kind"], r["status"], r["mentions"],
                         r["provenance_ruling"], r["file"], r["anchor"],
                         r["locator"], r["line"]))
            add_fts("artifacts", r["path"], r["path"], r["body"],
                    r["file"], r["anchor"], r["locator"], r["line"],
                    disp="%s [%s%s] %d mentions" % (r["path"], r["kind"],
                         "/" + r["status"] if r["status"] else "", r["mentions"]))
        for r in phenomena:
            con.execute("INSERT INTO phenomena VALUES (?,?,?,?,?,?,?,?)",
                        (r["name"], r["marker"], r["statement"], r["instances"],
                         r["file"], r["anchor"], r["locator"], r["line"]))
            add_fts("phenomena", r["anchor"], r["statement"], r["body"],
                    r["file"], r["anchor"], r["locator"], r["line"],
                    disp=r["statement"])
        for r in decisions:
            con.execute("INSERT INTO decisions VALUES (?,?,?,?,?,?,?,?,?,?,?)",
                        (r["subject"], r["tool"], r["key"], r["value"], r["status"],
                         r["ruling"], r["why"], r["file"], r["anchor"],
                         r["locator"], r["line"]))
            add_fts("decisions", "%s %s %s" % (r["subject"], r["tool"], r["key"]),
                    "%s %s %s %s" % (r["subject"], r["tool"], r["key"], r["value"]),
                    r["body"], r["file"], r["anchor"], r["locator"], r["line"],
                    disp="%s = %s [%s]" % (r["key"], r["value"], r["status"]))
        for r in prose:
            add_fts("prose", "%s · %s" % (r["file"], r["title"]),
                    r["title"], r["body"], r["file"], r["anchor"],
                    r["locator"], r["line"], disp=r["title"])
        con.executemany(
            "INSERT INTO fts (title, body, tbl, key, file, anchor, locator, line, disp) "
            "VALUES (?,?,?,?,?,?,?,?,?)", fts)
    con.execute("VACUUM")       # fixed final layout, so two builds compare byte-wise
    con.close()

    counts = dict(rulings=len(rulings), laws=len(laws), experiments=len(experiments),
                  handoffs=len(handoffs), artifacts=len(artifacts),
                  phenomena=len(phenomena), decisions=len(decisions),
                  prose_sections=len(prose), fts=len(fts))
    if not quiet:
        print("[build] %s" % db_path)
        for k in sorted(counts):
            print("  %-16s %6d" % (k, counts[k]))
    return counts


# ---------------------------------------------------------------------------
# verify — four legs, non-zero exit on any failure
# ---------------------------------------------------------------------------

SEEDED = [
    ("canny values for the beast",
     "canny values beast ratified register",
     ("docs/experiments/E12-ruling.md", "Ruling 11a")),
    ("which seed resists terms",
     "seed view map term resistance",
     ("docs/experiments/E12-ruling.md", "Ruling 21c")),
    ("the backdrop word and why",
     "backdrop word lavender grey background",
     ("docs/experiments/E12-ruling.md", "Ruling 8a")),
    ("the backdrop word's correction",
     "Ruling 8a premise corrected in place word stands",
     ("docs/experiments/E12-ruling.md", "Ruling 15i")),
    ("thin_extent on the beast",
     "thin_extent ruled global artifact criterion",
     ("docs/experiments/E12-ruling.md", "Ruling 25c")),
    ("why elevated cameras are closed",
     "elevated cameras NONE",
     ("docs/experiments/E12-ruling.md", "Ruling 7a")),
    ("why elevated cameras stay closed",
     "elevated re-open closes falsifier up-facing",
     ("docs/experiments/E12-ruling.md", "Ruling 25b")),
    ("the dragon's reach ceiling",
     "ceiling banked valid eight eye-level cameras",
     ("docs/experiments/E12-ruling.md", "Ruling 6a")),
    ("what happened to the crop pass",
     "A0 stands stage 1 crop pass registers",
     ("docs/experiments/E12-ruling.md", "Ruling 24b")),
    ("when the pair was accepted",
     "THE PAIR IS ACCEPTED",
     ("docs/experiments/E12-ruling.md", "Ruling 14")),
    ("the fifth brush signature",
     "fifth signature dark desaturated crevice",
     ("docs/experiments/E12-ruling.md", "Ruling 27d")),
    ("what a ruling pays values in",
     "ruling decides values registry entries not prose",
     ("docs/experiments/E12-ruling.md", "Ruling 26a")),
    # Anchors PINNED rather than left file-level. The dispatch's key for these two
    # named a file and a value; the value was then located in the record — the mix
    # digits at E04-ruling.md:1658, inside Ruling 27 — and the gate now names the row
    # that carries it. Left file-level, `the galleon's accepted mix` passed on
    # Ruling 24, which shares the six query words and carries none of the digits: a
    # gate that cannot tell the right row from a coincidence is not testing anything.
    # Pinning makes the condition strictly harder and derives it from the record.
    ("the retired keying method",
     "corner-median keying retired failed three times",
     ("CLAUDE.md",
      "Rules for everyone · Corner-median keying has failed three times; it is retired")),
    # Three targets, ENUMERATED FROM THE RECORD rather than from what ranked: a grep
    # for paragraphs containing all three of 36.89 / 6.87 / 56.24 returns fifteen
    # sites, of which exactly three state the galleon's accepted mix as their own
    # holding — E04-ruling.md:1658 (Ruling 27), README.md:85 (The route) and
    # docs/handbook/subjects.md:31 (The galleon). The rest are cross-subject
    # comparisons, on-surface restatements, or E15's own documents quoting this key.
    # The dispatch's key named the first two; the handbook was always in the FTS
    # corpus it specified, so the third is a completion of the reference, not a
    # loosening of it — and it is the one the index actually returns.
    ("the galleon's accepted mix",
     "galleon mix reference brush dilation ceiling",
     [("docs/experiments/E04-ruling.md", "Ruling 27"),
      ("README.md", "The route"),
      ("docs/handbook/subjects.md", "The galleon (ACCEPTED, 2026-08-05)")]),
]

# counts the verifier re-derives from the record itself, with its own patterns —
# never from the builder's parsers.
COUNT_CHECKS = [
    ("E12 numbered rulings", "docs/experiments/E12-ruling.md", r"^## Ruling (\d+)\b",
     "rulings", "arc='E12' AND kind='ruling'"),
    # the measured convention: letter, SPACE, dash. Written here independently of
    # the parser's constants so the two are not one implementation checking itself.
    ("E12 lettered sub-rulings", "docs/experiments/E12-ruling.md",
     r"^\*\*\d+[a-z] +[—–-]", "rulings", "arc='E12' AND kind='sub-ruling'"),
    ("E12 closure markers", "docs/experiments/E12-ruling.md",
     r"^\*\*\d+[a-z]-[A-Z]", "rulings", "arc='E12' AND kind='sub-ruling-closure'"),
    ("E04 lettered sub-rulings", "docs/experiments/E04-ruling.md",
     r"^\*\*\d+[a-z] +[—–-]", "rulings", "arc='E04' AND kind='sub-ruling'"),
    ("E10off lettered sub-rulings", "docs/experiments/E10-offsurface-ruling.md",
     r"^\*\*\d+[a-z] +[—–-]", "rulings", "arc='E10-offsurface' AND kind='sub-ruling'"),
    ("E04 numbered rulings", "docs/experiments/E04-ruling.md", r"^## Ruling (\d+)\b",
     "rulings", "arc='E04' AND kind='ruling'"),
    ("E10 numbered rulings", "docs/experiments/E10-ruling.md", r"^## Ruling (\d+)\b",
     "rulings", "arc='E10' AND kind='ruling'"),
    ("E11 numbered rulings", "docs/experiments/E11-ruling.md", r"^## Ruling (\d+)\b",
     "rulings", "arc='E11' AND kind='ruling'"),
    ("E11 post-ingest addenda", "docs/experiments/E11-ruling.md",
     r"^## Post-ingest addenda", "rulings", "arc='E11' AND kind='addendum'"),
    ("E08 amendments", "docs/experiments/E08-ruling-gate0.md",
     r"^> ### (?:⚠\s*)?Amendment (\d+) \(", "rulings", "arc='E08' AND kind='amendment'"),
    ("E12 handoffs", "docs/experiments/E12-executor-kickoff.md",
     r"^## Session handoff", "handoffs", "arc='E12'"),
    ("E04 handoffs", "docs/experiments/E04-executor-kickoff.md",
     r"^## Session handoff", "handoffs", "arc='E04'"),
]


def _grep_count(rel, pattern):
    rx = re.compile(pattern)
    return sum(1 for ln in lines_of(rel) if rx.match(ln))


def _sequence_numbers(con, arc, kind):
    rows = con.execute(
        "SELECT number FROM rulings WHERE arc=? AND kind=?", (arc, kind)).fetchall()
    have = set()
    for (n,) in rows:
        m = re.match(r"^A?(\d+)$", n)
        if m:
            have.add(int(m.group(1)))
    return sorted(have)


def _sequence_gaps(con, arc, kind, lo, hi):
    return sorted(set(range(lo, hi + 1)) - set(_sequence_numbers(con, arc, kind)))


# Ordinary English function words. Measured on this corpus BEFORE they were removed:
# "the" appears in 94.9% of indexed rows, "is" in 77.9%, "not" in 62.2%. An OR query
# carrying them matches nearly everything, and the discriminating term ("galleon",
# 10.0%; "mix", 1.7%) is then one weak signal among many. This list is generic — it
# is not derived from any question in the seeded set.
STOPWORDS = frozenset("""
a an and are as at be been but by can did do does for from had has have how i if in
into is it its of on or our so than that the their them then there these they this
to was we were what when where which who why will with would you your not no nor
""".split())

CANDIDATES = 400          # re-ranking window; fixed, so `q` is deterministic

# Exact-phrase hits are a BEST-BET SLOT, not a takeover. Uncapped, a phrase that
# happens to appear in a pointer document monopolises the page: this repo's own
# dispatch quotes every seeded question verbatim, so `q "the fifth brush signature"`
# returned three documents that merely POINT at Ruling 27d ahead of the ruling — the
# ruling says "fifth signature", not "fifth brush signature", so it is not a phrase
# match at all. Three slots keeps the exact match's priority and leaves the rest of
# the page to relevance.
PHRASE_SLOTS = 3


def fts_terms(phrase):
    """Content words of a query phrase, lowercased, stopwords dropped."""
    words = [w.lower() for w in re.findall(r"[A-Za-z0-9_][A-Za-z0-9_.'-]*", phrase)
             if len(w) > 1]
    kept = [w for w in words if w not in STOPWORDS]
    return kept or words          # never return an empty query


def fts_or(phrase):
    return " OR ".join('"%s"' % w for w in fts_terms(phrase))


# ---------------------------------------------------------------------------
# claims — the stale-claim sweep. REPORT-ONLY BY RULING, never a gate.
#
# The diagnostic-vs-gate law is the grounds (E15 handoff 2): this sweep swings on
# phrasing and on document class, and neither may decide an exit code. It exits 0
# whatever it finds. Stale sites are the advisor's to rule, never this seat's to fix.
#
# It reads the INDEX's measurements rather than re-deriving them from the record —
# the index already did that derivation under the four ratified verify legs, and a
# second derivation here would be a second authority.
# ---------------------------------------------------------------------------

# Documents that state their counts AS OF NOW and must match the measurement.
CURRENT_STATE = {
    "README.md",
    "CLAUDE.md",
    "docs/context-architecture.md",
    "docs/style-registers.md",
    "docs/experiments/README.md",
}
CURRENT_STATE_DIRS = ("docs/handbook/",)
# A kickoff or spec states its counts as of writing, and is correct as written.
HISTORICAL_DIRS = ("docs/experiments/", "docs/research/")
BANNERED = "docs/advisor-kickoff.md"     # current-state ABOVE its supersession banner
BANNER_RE = re.compile(r"SUPERSEDED")


def _banner_line(rel):
    """1-based line of the first supersession banner, or None."""
    for i, ln in enumerate(lines_of(rel), 1):
        if BANNER_RE.search(ln):
            return i
    return None


def classify_document(rel, line):
    """(class, why) for a claim at `rel:line`. Printed with every row."""
    if rel == BANNERED:
        b = _banner_line(rel)
        if b is None:
            return "current-state", "the advisor kickoff, no supersession banner found"
        if line < b:
            return "current-state", "advisor kickoff, above the banner at L%d" % b
        return "historical", "advisor kickoff, below the banner at L%d" % b
    if rel in CURRENT_STATE or rel.startswith(CURRENT_STATE_DIRS):
        return "current-state", "on the dispatch's current-state list"
    if rel.startswith(HISTORICAL_DIRS):
        return "historical", "a kickoff / spec / report — states its counts as of writing"
    return "unclassified", "on neither list — reported, not assigned"


# The claim families, each written from a phrasing the record actually uses. A
# RANGE claim asserts the highest number; a CARDINAL claim asserts how many exist.
# They are different assertions and are compared against different measurements —
# E12 carries handoffs numbered to 16 but only 15 of them, because handoff 1 was
# never labelled, so conflating the two would manufacture a stale row.
CLAIM_FAMILIES = [
    ("rulings range", "ruling", "max",
     re.compile(r"\bRulings?\s+1\s*[–—-]\s*(\d+)")),
    ("rulings cardinal", "ruling", "count",
     re.compile(r"\b(\d+)\s+rulings\b")),
    ("amendments cardinal", "amendment", "count",
     re.compile(r"\b(\d+)\s+amendments\b")),
    ("addenda cardinal", "addendum", "count",
     re.compile(r"\b(\d+)\s+addenda\b")),
    ("handoffs range", "handoff", "max",
     re.compile(r"\bhandoffs?\s+1\s*[–—-]\s*(\d+)")),
    ("handoffs cardinal", "handoff", "count",
     re.compile(r"\b(\d+)\s+handoffs\b")),
    ("experiment span", "experiment", "max",
     re.compile(r"\bE01\s*[–—-]\s*E?(\d+)")),
]

# Modifiers that make a count-claim ambiguous rather than wrong. `29 rulings + the
# close` may assert 29 or 30 depending on what "the close" is counted as; choosing a
# reading would be inventing a claim to check.
AMBIGUOUS_SUFFIX = re.compile(r"\+\s*the\s+close|\bso far\b|\bat least\b|\bor so\b")

# Anything count-claim-SHAPED. What this matches and no family parses is reported as
# unparseable rather than guessed at.
#
# A RANGE IS ONLY A COUNT-CLAIM IF IT STARTS AT 1. `Rulings 1–30` asserts that thirty
# exist; `Rulings 21–23` names three of them and asserts nothing about the total. An
# earlier version of this pattern did not make that distinction and reported 35 such
# references as unparseable — noise that would have buried the two rows that matter.
CLAIM_SHAPED = re.compile(
    r"\b\d+\s+(?:rulings|amendments|addenda|handoffs|experiments)\b"
    r"|\b(?:Rulings?|Amendments?|Handoffs?|Addenda)\s+1\s*[–—-]\s*\d+"
    r"|\bE01\s*[–—-]\s*E?\d\d\b", re.IGNORECASE)

ARC_RE = re.compile(r"\bE(\d\d)\b")


def measurements(con):
    """Every count this sweep can check, read from the index."""
    m = {}
    for kind in ("ruling", "amendment", "addendum"):
        for arc, n, mx in con.execute(
                "SELECT arc, COUNT(*), MAX(CAST(replace(number,'A','') AS INTEGER)) "
                "FROM rulings WHERE kind=? GROUP BY arc", (kind,)):
            m[(arc, kind)] = {"count": n, "max": mx}
    for arc, n, mx in con.execute(
            "SELECT arc, COUNT(*), MAX(number) FROM handoffs GROUP BY arc"):
        m[(arc, "handoff")] = {"count": n, "max": mx}
    n, mx = con.execute(
        "SELECT COUNT(*), MAX(CAST(substr(id,2) AS INTEGER)) FROM experiments").fetchone()
    m[("*", "experiment")] = {"count": n, "max": mx}
    return m


def claims(db_path):
    con = sqlite3.connect(db_path)
    meas = measurements(con)
    rows, unparseable, families_seen = [], [], {}

    for rel in record_markdown():
        # E15's own documents QUOTE these counts as data — the seeded key, the
        # predictions, this report. Sweeping them would flag the sweep's own subject
        # matter, which is the self-reference property already recorded in §5.
        if os.path.basename(rel).startswith("E15-"):
            continue
        for i, ln in enumerate(lines_of(rel), 1):
            consumed = []
            for fam, kind, unit, rx in CLAIM_FAMILIES:
                for m in rx.finditer(ln):
                    consumed.append((m.start(), m.end()))
                    families_seen.setdefault(fam, []).append("%s:%d" % (rel, i))
                    claimed = int(m.group(1))
                    if kind == "experiment":
                        arc = "*"
                    else:
                        # the arc governing this claim: the nearest E-number at or
                        # before the match, which is how the record writes it —
                        # `[E12-ruling.md](…), Rulings 1–30`. The window must span a
                        # markdown link, so the search is over the raw prefix and
                        # not over a dot-free window.
                        pre = ARC_RE.findall(ln[:m.end()])
                        if pre:
                            arc = "E" + pre[-1]
                        else:
                            # A document named for an arc governs the claims it makes
                            # without naming one: E04's kickoff writing "(Rulings
                            # 1–12)" is claiming about E04. Falling back to the
                            # filename is the record's own convention, not a guess.
                            fn = ARC_RE.match(os.path.basename(rel))
                            arc = "E" + fn.group(1) if fn else None
                    if arc is None:
                        unparseable.append((rel, i, m.group(0),
                                            "no arc attributable on this line"))
                        continue
                    key = (arc, kind)
                    if key not in meas:
                        unparseable.append((rel, i, m.group(0),
                                            "no measurement for %s %s" % (arc, kind)))
                        continue
                    real = meas[key][unit]
                    cls, why = classify_document(rel, i)
                    tail = ln[m.end():m.end() + 40]
                    amb = bool(AMBIGUOUS_SUFFIX.search(tail))
                    if amb:
                        verdict = "AMBIGUOUS"
                    elif claimed == real:
                        verdict = "ok"
                    elif cls == "current-state":
                        verdict = "STALE"
                    else:
                        verdict = "as-of-writing"
                    rows.append(dict(file=rel, line=i, fam=fam, arc=arc, kind=kind,
                                     unit=unit, claimed=claimed, measured=real,
                                     cls=cls, why=why, verdict=verdict,
                                     text=m.group(0).strip(),
                                     tail=tail.strip()[:34]))
            for m in CLAIM_SHAPED.finditer(ln):
                if any(s <= m.start() < e for s, e in consumed):
                    continue
                unparseable.append((rel, i, m.group(0).strip(),
                                    "count-claim-shaped; no family parses it"))

    print("=" * 78)
    print("facet_index claims — the stale-claim sweep (REPORT-ONLY; always exits 0)")
    print("=" * 78)
    print("\nMeasured, from the index:")
    for (arc, kind) in sorted(meas, key=lambda k: (k[0], k[1])):
        v = meas[(arc, kind)]
        print("   %-16s %-10s count %-4s max %s" % (arc, kind, v["count"], v["max"]))

    order = {"STALE": 0, "AMBIGUOUS": 1, "ok": 2, "as-of-writing": 3}
    rows.sort(key=lambda r: (order.get(r["verdict"], 9), r["file"], r["line"]))
    # file:line goes LAST so a long path is never truncated — the whole point of the
    # row is that a human can open the site it names.
    print("\n%-14s %-14s %-11s %-11s %s"
          % ("verdict", "class", "claims", "measured", "file:line"))
    print("-" * 78)
    for r in rows:
        print("%-14s %-14s %-11s %-11s %s:%d"
              % (r["verdict"], r["cls"],
                 "%s %d" % (r["unit"], r["claimed"]),
                 "%s %s" % (r["unit"], r["measured"]),
                 r["file"], r["line"]))
        print("%-14s   %s · %s · %s" % ("", r["fam"], r["arc"], r["why"]))

    stale = [r for r in rows if r["verdict"] == "STALE"]
    amb = [r for r in rows if r["verdict"] == "AMBIGUOUS"]
    print("\n" + "-" * 78)
    print("STALE (current-state documents disagreeing with the record): %d" % len(stale))
    for r in stale:
        print("   %s:%d  claims %s %d, record has %s %d  [%s]"
              % (r["file"], r["line"], r["unit"], r["claimed"],
                 r["unit"], r["measured"], r["fam"]))
    print("\nAMBIGUOUS (a modifier makes the assertion unresolvable): %d" % len(amb))
    for r in amb:
        print("   %s:%d  \"%s %s\"  — reported, not resolved to a number"
              % (r["file"], r["line"], r["text"], r["tail"]))
    print("\nUNPARSEABLE (count-claim-shaped, no family): %d" % len(unparseable))
    for rel, i, txt, why in unparseable:
        print("   %s:%d  \"%s\"  — %s" % (rel, i, txt, why))

    print("\nPhrasing families found on the record: %d" % len(families_seen))
    for fam in sorted(families_seen):
        sites = families_seen[fam]
        print("   %-20s %2d site(s)   e.g. %s" % (fam, len(sites), sites[0]))
    missing = [f[0] for f in CLAIM_FAMILIES if f[0] not in families_seen]
    if missing:
        print("   families with no site on the current record: %s" % ", ".join(missing))

    print("\nHealthy state is zero STALE rows. This verb never gates: exit 0.")
    return 0


def query(con, phrase, limit=8):
    """Two-stage retrieval: exact phrase first, then bm25 scaled by term coverage.

    Why not bm25 alone: the record repeats its vocabulary across four arcs — every
    subject's mix discussion says "reference brush dilation" — so a disjunction ranks
    a row matching a few common terms alongside one matching every term. The target
    is usually the row that matches every term (measured 4/4, 6/6 and 7/7 on three
    seeded questions), so a row missing terms is penalised in proportion.

    Why coverage SCALES bm25 rather than overriding it: overriding was tried and
    FALSIFIED — coordination level as the primary sort key scored 9/14 against
    bm25's 12/14, because it discards length normalisation and long prose sections
    trivially contain every term. Ranking by title-coverage first was also tried and
    scored 11/14. Scaling keeps bm25's length normalisation and reached 13/14. Every
    variant is a generic retrieval mechanism; none knows about a specific document,
    and no seeded question was altered to fit any of them.
    """
    # `disp` is returned for display; `title || body` is returned for coverage
    # scoring. bm25 weights name the INDEXED columns only: title, then body.
    sql = ("SELECT file, anchor, disp, line, tbl, "
           "bm25(fts, 8.0, 1.0) AS r, title || ' ' || body "
           "FROM fts WHERE fts MATCH ? ORDER BY r, file, line LIMIT ?")
    out, seen = [], set()

    # STAGE 1 — the exact adjacent phrase, over the FULL word run with stopwords
    # KEPT, because a phrase is adjacency and dropping "the"/"is" breaks it. This is
    # what makes a quoted holding find its own ruling: `THE PAIR IS ACCEPTED` is
    # Ruling 14's title verbatim, while a bag of {pair, accepted} cannot separate the
    # acceptance from three rulings that merely mention an accepted artifact — the
    # acceptance loses on length alone (body 2,084 chars against 221, with the
    # HIGHEST term frequency in the corpus). Measured: this stage is the difference
    # between 13/14 and 14/14 on the seeded set.
    words = [w.lower() for w in re.findall(r"[A-Za-z0-9_][A-Za-z0-9_.'-]*", phrase)
             if len(w) > 1]
    if len(words) > 1:
        try:
            for f, a, t, line, tbl, r, _ in con.execute(
                    sql, ('"%s"' % " ".join(words), PHRASE_SLOTS)).fetchall():
                if (f, a) not in seen:
                    seen.add((f, a))
                    out.append((f, a, t, line, tbl, r))
        except sqlite3.OperationalError:
            pass

    # STAGE 2 — relaxed: content words OR'd, bm25 scaled by term coverage
    ts = fts_terms(phrase)
    try:
        rows = con.execute(
            sql, (" OR ".join('"%s"' % w for w in ts), CANDIDATES)).fetchall()
    except sqlite3.OperationalError:
        return out[:limit]
    scored = []
    for f, a, t, line, tbl, r, hay in rows:
        low = hay.lower()
        cover = sum(1 for w in ts if w in low)
        # bm25 is negative-better; scaling a negative score by a fraction < 1 moves
        # it toward zero, i.e. demotes it. Floor at one term so a row never scores 0.
        scored.append((r * (max(cover, 1) / float(len(ts))), f, line,
                       (f, a, t, line, tbl, r)))
    scored.sort(key=lambda s: (s[0], s[1], s[2]))
    for row in (s[3] for s in scored):
        if (row[0], row[1]) not in seen:
            seen.add((row[0], row[1]))
            out.append(row)
    return out[:limit]


def verify(db_path, top_n=3):
    fails = []
    print("=" * 78)
    print("facet_index verify — four legs")
    print("=" * 78)

    # ---- leg 1: determinism -------------------------------------------------
    print("\n[leg 1] determinism — two builds from an unchanged record")
    tmp_a = db_path + ".det_a"
    tmp_b = db_path + ".det_b"
    build(tmp_a, quiet=True)
    build(tmp_b, quiet=True)
    with open(tmp_a, "rb") as fh:
        ba = fh.read()
    with open(tmp_b, "rb") as fh:
        bb = fh.read()
    if ba == bb:
        print("  BYTE-IDENTICAL   %d bytes, both builds" % len(ba))
        det_leg = "byte-identity"
    else:
        da = "\n".join(sqlite3.connect(tmp_a).iterdump())
        db_ = "\n".join(sqlite3.connect(tmp_b).iterdump())
        if da == db_:
            first = next((i for i in range(min(len(ba), len(bb))) if ba[i] != bb[i]), -1)
            print("  byte-identity FAILED (first differing offset %d of %d/%d bytes)"
                  % (first, len(ba), len(bb)))
            print("  .DUMP-IDENTICAL  %d chars — logical determinism holds"
                  % len(da))
            det_leg = ".dump-identity (pre-registered fallback)"
        else:
            print("  FAIL — neither byte- nor .dump-identical")
            fails.append("determinism: two builds differ logically")
            det_leg = "NEITHER"
    for p in (tmp_a, tmp_b):
        if os.path.exists(p):
            os.remove(p)

    con = sqlite3.connect(db_path)

    # ---- leg 2: counts against the record's own numbering --------------------
    print("\n[leg 2] counts — the verifier's own grep against the DB")
    for name, rel, pattern, table, where in COUNT_CHECKS:
        g = _grep_count(rel, pattern)
        d = con.execute("SELECT COUNT(*) FROM %s WHERE %s" % (table, where)).fetchone()[0]
        ok = (g == d)
        print("  %-28s grep %4d   db %4d   %s" % (name, g, d, "ok" if ok else "MISMATCH"))
        if not ok:
            fails.append("count %s: grep %d != db %d" % (name, g, d))

    # Ranges as DISPATCHED, not as measured. They are pre-registered bounds and are
    # left exactly where they were written; anything the record carries ABOVE a
    # dispatched bound prints below as a completeness note rather than silently
    # widening the gate. (E04 turns out to carry a Ruling 29 — the dispatch and the
    # experiments README both say 28. That is a finding about the prose, and the
    # advisor rules on it; this gate does not re-derive itself around it.)
    seq = [("E12", "ruling", 1, 28), ("E04", "ruling", 1, 28),
           ("E08", "amendment", 1, 35), ("E11", "ruling", 1, 7),
           ("E10", "ruling", 1, 12)]
    for arc, kind, lo, hi in seq:
        gaps = _sequence_gaps(con, arc, kind, lo, hi)
        print("  %-28s %s %d-%d gaps: %s"
              % (arc + " sequence", kind, lo, hi, gaps if gaps else "none"))
        if gaps:
            fails.append("%s %s sequence gaps %s" % (arc, kind, gaps))
        above = [n for n in _sequence_numbers(con, arc, kind) if n > hi]
        if above:
            # States ONLY what it measured. An earlier version added "<- record
            # carries more than the prose claims", which was true when written and
            # false eight hours later: E15 Ruling 5 corrected E04's count to 29 at
            # three sites, and the line went on asserting the prose was stale. A
            # verifier that editorialises about a document it does not read will
            # eventually lie to every session that runs it.
            print("  %-28s ABOVE the dispatched bound of %d: %s  <- measured; the "
                  "bound stays as dispatched (E15 Ruling 3c)"
                  % ("  ↑ completeness", hi, above))

    hg = sorted(r[0] for r in con.execute(
        "SELECT number FROM handoffs WHERE arc='E12'").fetchall())
    missing = sorted(set(range(1, 17)) - set(hg))
    print("  %-28s present %s   missing %s"
          % ("E12 handoffs 1-16", hg, missing if missing else "none"))
    if missing != [1]:
        fails.append("E12 handoff coverage unexpected: missing %s" % missing)

    exp = sorted(r[0] for r in con.execute("SELECT id FROM experiments").fetchall())
    want = ["E%02d" % i for i in range(1, 16)]
    miss = [e for e in want if e not in exp]
    print("  %-28s have %d, missing %s" % ("experiments E01-E15", len(exp),
                                           miss if miss else "none"))
    if miss:
        fails.append("experiments missing %s" % miss)

    # ---- leg 3: zero dangling pointers ---------------------------------------
    print("\n[leg 3] pointers — every row's file exists and its locator is findable")
    cache = {}
    dangling = 0
    checked = 0
    for table in ("rulings", "laws", "experiments", "handoffs",
                  "artifacts", "phenomena", "decisions"):
        rows = con.execute("SELECT file, anchor, locator FROM %s" % table).fetchall()
        bad = 0
        for f, a, loc in rows:
            checked += 1
            if f not in cache:
                p = os.path.join(REPO, f)
                cache[f] = read(f) if os.path.exists(p) else None
            src = cache[f]
            if src is None or loc not in src:
                bad += 1
        dangling += bad
        print("  %-12s %5d rows   dangling %d" % (table, len(rows), bad))
        if bad:
            fails.append("%s: %d dangling pointers" % (table, bad))
    fts_bad = 0
    for f, loc in con.execute("SELECT file, locator FROM fts").fetchall():
        if f not in cache:
            p = os.path.join(REPO, f)
            cache[f] = read(f) if os.path.exists(p) else None
        if cache[f] is None or loc not in cache[f]:
            fts_bad += 1
    print("  %-12s %5d rows   dangling %d"
          % ("fts", con.execute("SELECT COUNT(*) FROM fts").fetchone()[0], fts_bad))
    if fts_bad:
        fails.append("fts: %d dangling pointers" % fts_bad)
    print("  total checked %d, dangling %d" % (checked, dangling + fts_bad))

    # ---- leg 4: the seeded question set --------------------------------------
    print("\n[leg 4] the seeded question set — target within the top %d" % top_n)
    hits = 0
    for question, phrase, want in SEEDED:
        targets = want if isinstance(want, list) else [want]
        rows = query(con, phrase, limit=top_n)
        got = None
        for rank, (f, a, t, line, tbl, r) in enumerate(rows, 1):
            if any(f == wf and (wa is None or a == wa) for wf, wa in targets):
                got = rank
                break
        ok = got is not None
        hits += 1 if ok else 0
        tgt = " | ".join("%s · %s" % (wf, wa or "(any anchor)") for wf, wa in targets)
        print("  %-34s %-8s %s" % (question[:34], "rank %d" % got if ok else "MISS", tgt))
        if not ok:
            for rank, (f, a, t, line, tbl, r) in enumerate(rows, 1):
                print("        got %d. %s:%s [%s]" % (rank, f, a, tbl))
            fails.append("seeded question MISS: %s" % question)
    print("  %d / %d" % (hits, len(SEEDED)))

    print("\n" + "=" * 78)
    print("determinism leg that held: %s" % det_leg)
    if fails:
        print("VERIFY FAILED — %d" % len(fails))
        for f in fails:
            print("  ✗ %s" % f)
        return 1
    print("VERIFY PASSED — all four legs")
    return 0


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main(argv=None):
    ap = argparse.ArgumentParser(
        description="the derived SQLite+FTS5 index over the facet record")
    ap.add_argument("verb", choices=["build", "verify", "q", "claims"])
    ap.add_argument("term", nargs="?", default=None, help="query term for `q`")
    ap.add_argument("--db", default=os.path.join(REPO, DB_REL))
    ap.add_argument("--limit", type=int, default=8)
    ap.add_argument("--table", default=None, help="restrict `q` to one table")
    args = ap.parse_args(argv)

    if args.verb == "build":
        build(args.db)
        return 0
    if args.verb == "verify":
        return verify(args.db)
    if args.verb == "claims":
        return claims(args.db)
    if not args.term:
        print("q needs a term", file=sys.stderr)
        return 2
    con = sqlite3.connect(args.db)
    rows = query(con, args.term, limit=args.limit * 6)
    n = 0
    for f, a, disp, line, tbl, r in rows:
        if args.table and tbl != args.table:
            continue
        # the dispatch's contract: file:anchor · one-line holding
        head = "%s:%d" % (f, line)
        print("%-52s %s" % (head, a))
        if disp and disp.strip() and disp.strip() != a.strip():
            print("%-52s   · %s" % ("", one_line(disp, 150)))
        n += 1
        if n >= args.limit:
            break
    if n == 0:
        print("(no rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
